(()=>{
const K='magnetMayhemSave';
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};
const write=s=>localStorage.setItem(K,JSON.stringify(s));
const day=()=>{const d=new Date();return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`};
const hash=s=>[...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7);
const MODS=[{name:'RAPID',desc:'Time is reduced by 28%.',tag:'SPEED RUN'},{name:'HAZARD RUSH',desc:'Extra hazards enter the field.',tag:'DANGER+'},{name:'DOUBLE SCORE',desc:'All score gains are doubled.',tag:'2X SCORE'},{name:'ICE FIELD',desc:'Your magnet shrinks for a tighter pull.',tag:'TIGHT FIELD'},{name:'NO SHIELD',desc:'No starting shield. Pure survival.',tag:'HARDCORE'},{name:'COMBO FEVER',desc:'Combos build faster, but decay faster.',tag:'CHAIN MODE'},{name:'LOW GRAVITY',desc:'Cores resist the magnet more strongly.',tag:'PULL DOWN'}];
function getChallenge(){const s=read(),max=Math.max(1,Math.min(Number(s.unlocked)||1,1000)),h=hash(day()),m=MODS[h%MODS.length];return{level:1+(h%max),modifier:m.name,description:m.desc,tag:m.tag,day:day(),seed:h}}
window.magnetDailyChallenge=getChallenge;
window.openDailyChallenge=()=>{const c=getChallenge(),ov=document.getElementById('overlay'),ok=document.getElementById('overlayKicker'),ot=document.getElementById('overlayTitle'),ox=document.getElementById('overlayText'),pb=document.getElementById('primaryBtn'),sb=document.getElementById('secondaryBtn');if(!ov)return;const s=read(),best=Number(s.challengeBest?.[c.day])||0,done=!!s.challengeDone?.[c.day],streak=Number(s.challengeStreak)||0;window.magnetChallengeActive=null;if(typeof g!=='undefined'&&g&&!g.over)g.paused=1;ov.classList.remove('hidden');ok.textContent=`DAILY CHALLENGE // ${c.day}`;ot.textContent=c.modifier;ox.innerHTML=`<div class="challenge-card"><b>FIELD ${c.level}</b><span>${c.tag}</span></div><p>${c.description}</p><div class="challenge-stats"><span><b>${best||'—'}</b><small>TODAY'S BEST</small></span><span><b>${streak}</b><small>DAY STREAK</small></span><span><b>+${50+c.level}</b><small>COIN REWARD</small></span></div>${done?'<div class="challenge-complete">✓ COMPLETED TODAY</div>':''}<small>New challenge every day at 00:00 UTC.</small>`;pb.textContent='PLAY CHALLENGE';pb.onclick=()=>{ov.classList.add('hidden');window.magnetChallengeActive=c;window.magnetChallengeRun=(window.magnetChallengeRun||0)+1;if(typeof start==='function')start(c.level)};sb.classList.add('hidden')};
const controls=document.querySelector('.controls');if(controls){const old=[...controls.querySelectorAll('button')].find(x=>/^(DAILY|CHALLENGE)$/.test(x.textContent.trim()));if(old)old.remove();const b=document.createElement('button');b.type='button';b.textContent='DAILY';b.className='controls button';b.id='dailyChallengeBtn';b.onclick=()=>window.openDailyChallenge();controls.prepend(b)}
})();