(()=>{
const K='magnetMayhemSave';
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};
const write=s=>localStorage.setItem(K,JSON.stringify(s));
const day=()=>{const d=new Date();return `${d.getUTCFullYear()}-${String(d.getUTCMonth()+1).padStart(2,'0')}-${String(d.getUTCDate()).padStart(2,'0')}`};
const hash=s=>[...s].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,7);
const MODS=[{name:'RAPID',desc:'Time is reduced by 28%.',tag:'SPEED RUN'},{name:'HAZARD RUSH',desc:'Extra hazards enter the field.',tag:'DANGER+'},{name:'DOUBLE SCORE',desc:'All score gains are doubled.',tag:'2X SCORE'},{name:'ICE FIELD',desc:'Your magnet shrinks for a tighter pull.',tag:'TIGHT FIELD'},{name:'NO SHIELD',desc:'No starting shield. Pure survival.',tag:'HARDCORE'},{name:'COMBO FEVER',desc:'Combos build faster, but decay faster.',tag:'CHAIN MODE'},{name:'LOW GRAVITY',desc:'Cores resist the magnet more strongly.',tag:'PULL DOWN'}];
function getChallenge(){const s=read(),max=Math.max(1,Math.min(Number(s.unlocked)||1,1000)),h=hash(day()),m=MODS[h%MODS.length];return{level:1+(h%max),modifier:m.name,description:m.desc,tag:m.tag,day:day(),seed:h}}
window.magnetDailyChallenge=getChallenge;
function recordChallenge(c){const s=read(),d=c.day,score=Math.floor(g.score);s.challengeBest=s.challengeBest||{};s.challengeDone=s.challengeDone||{};s.challengeBest[d]=Math.max(Number(s.challengeBest[d])||0,score);if(!s.challengeDone[d]){s.challengeDone[d]=1;s.challengeLastCompleted=s.challengeLastCompleted||'';const last=s.challengeLastCompleted;if(last){const a=new Date(last+'T00:00:00Z'),b=new Date(d+'T00:00:00Z');s.challengeStreak=Math.round((b-a)/86400000)===1?(Number(s.challengeStreak)||0)+1:1}else s.challengeStreak=1;s.challengeLastCompleted=d;s.coins=(Number(s.coins)||0)+50+c.level}write(s)}
const originalStart=window.start;if(originalStart)window.start=(n)=>{originalStart(n);const c=window.magnetChallengeActive;if(!c)return;if(c.modifier==='RAPID')g.time*=.72;if(c.modifier==='ICE FIELD')g.m.r=23;if(c.modifier==='NO SHIELD')g.shield=0;if(c.modifier==='HAZARD RUSH'){for(let i=0;i<Math.min(5,2+Math.floor(g.n/100));i++){let p={x:35+Math.random()*(W-70),y:55+Math.random()*(H-90)};g.haz.push({x:p.x,y:p.y,r:18+Math.random()*7,a:Math.random()*TAU,phase:Math.random()*TAU,orbit:30+Math.random()*35,speed:.7+Math.random()*.6})}}if(c.modifier==='COMBO FEVER'){g._challengeComboTimer=0;g._challengeComboPulse=0}if(c.modifier==='LOW GRAVITY')g._challengePullRadius=20};
const originalUpdate=window.update;if(originalUpdate)window.update=(dt)=>{const c=window.magnetChallengeActive;if(!c||!g||g.over)return originalUpdate(dt);if(c.modifier==='LOW GRAVITY'){const r=g.m.r;g.m.r=g._challengePullRadius||20;originalUpdate(dt);if(g&&!g.over)g.m.r=r;return}if(c.modifier==='COMBO FEVER'){g._challengeComboTimer=(g._challengeComboTimer||0)+dt;g._challengeComboPulse=(g._challengeComboPulse||0)+dt;originalUpdate(dt);if(g&&!g.over){if(g._challengeComboPulse>1.5&&g.combo>1){g.combo--;g._challengeComboPulse=0}g._challengeComboTimer=0}}else originalUpdate(dt)};
const originalFinish=window.finish;if(originalFinish)window.finish=(win)=>{const c=window.magnetChallengeActive,s=read();s.stats=s.stats||{wins:0,cores:0,stars:0,bosses:0};if(win){s.stats.wins=(Number(s.stats.wins)||0)+1;const z=typeof cfg==='function'?cfg(g.n):null,stars=z?(g.time>z.time*.45?3:g.time>z.time*.2?2:1):1;s.stats.stars=(Number(s.stats.stars)||0)+stars;if(g.n%10===0)s.stats.bosses=(Number(s.stats.bosses)||0)+1;if(c)recordChallenge(c);else write(s)}return originalFinish(win)};
const originalPull=window.pull;if(originalPull)window.pull=(c)=>{const active=window.magnetChallengeActive,before=g.score;originalPull(c);if(active&&active.modifier==='COMBO_FEVER'){g.combo=Math.min(15,g.combo+1);g._challengeComboPulse=0}const s=read();s.stats=s.stats||{wins:0,cores:0,stars:0,bosses:0};s.stats.cores=(Number(s.stats.cores)||0)+1;if(active&&active.modifier==='DOUBLE SCORE'){const delta=g.score-before;g.score+=delta}write(s)};
window.openDailyChallenge=()=>{const c=getChallenge(),ov=document.getElementById('overlay'),ok=document.getElementById('overlayKicker'),ot=document.getElementById('overlayTitle'),ox=document.getElementById('overlayText'),pb=document.getElementById('primaryBtn'),sb=document.getElementById('secondaryBtn');if(!ov)return;const s=read(),best=Number(s.challengeBest?.[c.day])||0,done=!!s.challengeDone?.[c.day],streak=Number(s.challengeStreak)||0;window.magnetChallengeActive=null;if(typeof g!=='undefined'&&g&&!g.over)g.paused=1;ov.classList.remove('hidden');ok.textContent=`DAILY CHALLENGE // ${c.day}`;ot.textContent=c.modifier;ox.innerHTML=`<div class="challenge-card"><b>FIELD ${c.level}</b><span>${c.tag}</span></div><p>${c.description}</p><div class="challenge-stats"><span><b>${best||'—'}</b><small>TODAY'S BEST</small></span><span><b>${streak}</b><small>DAY STREAK</small></span><span><b>+${50+c.level}</b><small>COIN REWARD</small></span></div>${done?'<div class="challenge-complete">✓ COMPLETED TODAY</div>':''}<small>New challenge every day at 00:00 UTC.</small>`;pb.textContent='PLAY CHALLENGE';pb.onclick=()=>{ov.classList.add('hidden');window.magnetChallengeActive=c;window.magnetChallengeRun=(window.magnetChallengeRun||0)+1;if(typeof start==='function')start(c.level)};sb.classList.add('hidden')};
const controls=document.querySelector('.controls');if(controls){const old=[...controls.querySelectorAll('button')].find(x=>/^(DAILY|CHALLENGE)$/.test(x.textContent.trim()));if(old)old.remove();const b=document.createElement('button');b.type='button';b.textContent='DAILY';b.className='controls button';b.id='dailyChallengeBtn';b.onclick=()=>window.openDailyChallenge();controls.prepend(b)}
})();