const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),comboEl=document.getElementById('combo'),levelEl=document.getElementById('level'),overlay=document.getElementById('overlay'),overlayKicker=document.getElementById('overlayKicker'),overlayTitle=document.getElementById('overlayTitle'),overlayText=document.getElementById('overlayText'),primaryBtn=document.getElementById('primaryBtn'),secondaryBtn=document.getElementById('secondaryBtn'),pauseBtn=document.getElementById('pauseBtn'),toast=document.getElementById('toast'),homeBtn=document.getElementById('homeBtn'),muteBtn=document.getElementById('muteBtn');
let W=0,H=0,dpr=1,last=0,game=null,audio=null,mute=false;
const TAU=Math.PI*2,MAX=1000,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){dpr=Math.min(2,devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(game){game.magnet.x=clamp(game.magnet.x,0,W);game.magnet.y=clamp(game.magnet.y,0,H)}}addEventListener('resize',resize);resize();
function load(){try{return JSON.parse(localStorage.getItem('magnetMayhemSave')||'{}')}catch{return{}}}let save=load();save.unlocked=Math.max(1,Math.min(MAX,save.unlocked||1));save.best=save.best||{};save.coins=save.coins||0;save.achievements=save.achievements||[];function persist(){localStorage.setItem('magnetMayhemSave',JSON.stringify(save))}
function seeded(n){const x=Math.sin(n*999.91)*43758.5453123;return x-Math.floor(x)}function cfg(l){return{cores:Math.min(14,3+Math.floor((l-1)/70)),hazards:Math.min(10,1+Math.floor(l/80)),time:Math.max(11,30-l*.012),speed:1+Math.floor((l-1)/25)*.13}}
function layout(l){const c=cfg(l),cores=[],hazards=[],used=[];function point(seed,gap){let x,y;for(let k=0;k<20;k++){x=(.07+seeded(seed+k*17)*.86)*W;y=(.1+seeded(seed+77+k*19)*.8)*H;if(Math.hypot(x-W/2,y-H/2)>Math.min(W,H)*.17&&!used.some(p=>Math.hypot(p.x-x,p.y-y)<gap))break}return{x,y}}for(let i=0;i<c.cores;i++){const p=point(l*31+i*13,55);used.push(p);cores.push({x:p.x,y:p.y,r:13,type:['cyan','pink','gold','violet'][(i+l)%4],alive:true,vx:0,vy:0})}for(let i=0;i<c.hazards;i++){const p=point(l*101+i*29,75);used.push(p);hazards.push({x:p.x,y:p.y,r:17+seeded(l*211+i)*10,a:seeded(l*271+i)*TAU,speed:(.4+seeded(l*313+i)*.8)*c.speed})}return{cores,hazards}}
function best(l){return save.best[l]||0}function award(id,text){if(save.achievements.includes(id))return;save.achievements.push(id);persist();showToast('ACHIEVEMENT  •  '+text);tone(880,.12,'triangle')}
function tone(f,d=.06,type='sine'){if(mute)return;if(!audio)try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch{return}try{if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}catch{}}
function toastMsg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastMsg.t);toastMsg.t=setTimeout(()=>toast.classList.remove('show'),1200)}
function hide(){overlay.classList.add('hidden')}function hud(){scoreEl.textContent=Math.floor(game.score);comboEl.textContent='x'+game.combo;levelEl.textContent=game.level}
function start(level=1){level=clamp(Math.floor(Number(level)||1),1,save.unlocked);const l=layout(level);game={level,score:0,combo:1,time:cfg(level).time,cores:l.cores,hazards:l.hazards,particles:[],rings:[],texts:[],magnet:{x:W/2,y:H/2,r:29},mouse:{x:W/2,y:H/2},drag:false,paused:false,over:false,won:false,shake:0};hide();hud();toastMsg('LEVEL '+level+'  •  BEST '+best(level))}
function finish(win){game.over=true;game.drag=false;if(!win){overlay.classList.remove('hidden');overlayKicker.textContent='RUN OVER';overlayTitle.textContent='MAGNET JAM';overlayText.innerHTML=`Level <b>${game.level}</b><br>Score <b>${Math.floor(game.score)}</b> · Best <b>${best(game.level)}</b><br><br>Reset your combo and try again.`;primaryBtn.textContent='TRY AGAIN';secondaryBtn.classList.add('hidden');primaryBtn.onclick=()=>start(game.level);return}const t=cfg(game.level).time,left=game.time,stars=left>t*.45?3:left>t*.2?2:1;game.score+=Math.floor(left*25)+stars*50;const old=best(game.level);if(game.score>old)save.best[game.level]=Math.floor(game.score);save.unlocked=Math.max(save.unlocked,Math.min(MAX,game.level+1));save.coins+=stars;persist();if(game.level>=10)award('ten','TEN DOWN');if(game.level>=100)award('hundred','CENTURY');if(game.level>=MAX)award('thousand','MAYHEM MASTER');overlay.classList.remove('hidden');overlayKicker.textContent='LEVEL COMPLETE';overlayTitle.textContent='LEVEL '+game.level;overlayText.innerHTML=`Score <b>${Math.floor(game.score)}</b> · ${'★'.repeat(stars)}${'☆'.repeat(3-stars)}<br>Best <b>${best(game.level)}</b> · Coins +<b>${stars}</b>`;primaryBtn.textContent=game.level<MAX?'NEXT LEVEL':'PLAY AGAIN';secondaryBtn.classList.remove('hidden');secondaryBtn.textContent='REPLAY LEVEL';primaryBtn.onclick=()=>game.level<MAX?start(game.level+1):start(game.level);secondaryBtn.onclick=()=>start(game.level);tone(660,.15,'triangle')}
function collect(c){c.alive=false;const gain=100*game.combo+Math.floor(game.time*5);game.score+=gain;game.combo=Math.min(12,game.combo+1);if(game.combo>=8)award('combo','CHAIN REACTION');if(!save.achievements.includes('first'))award('first','FIRST PULL');game.rings.push({x:c.x,y:c.y,r:5,life:.45,max:.45,col:color(c.type)});game.texts.push({x:c.x,y:c.y,text:'+'+gain,life:.8,col:color(c.type)});burst(c.x,c.y,color(c.type),22);tone(280+game.combo*55,.05)}
function hit(c){game.combo=1;game.score=Math.max(0,game.score-75);c.x=rand(35,W-35);c.y=rand(45,H-45);c.vx=c.vy=0;game.shake=.25;burst(c.x,c.y,'#ff5577',24);tone(95,.1,'sawtooth')}
function color(t){return{cyan:'#5ce1ff',pink:'#ff69bc',gold:'#ffd66b',violet:'#a98cff'}[t]||'#fff'}function burst(x,y,c,n=18){for(let i=0;i<n;i++){const a=rand(0,TAU),s=rand(50,220);game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.3,.8),max:.8,col:c,r:rand(1,3)})}}
function update(dt){if(game.paused||game.over)return;game.time-=dt;if(game.time<=0){finish(false);return}const m=game.magnet,cfgNow=cfg(game.level);for(const c of game.cores){if(!c.alive)continue;const dx=m.x-c.x,dy=m.y-c.y,d=Math.hypot(dx,dy)||1,pull=game.drag?Math.min(1500,90000/(d*d+170)):0;c.vx+=(dx/d)*pull*dt;c.vy+=(dy/d)*pull*dt;c.vx*=Math.pow(.035,dt);c.vy*=Math.pow(.035,dt);c.x=clamp(c.x+c.vx*dt,c.r,W-c.r);c.y=clamp(c.y+c.vy*dt,c.r,H-c.r);if(d<m.r+c.r+8)collect(c)}for(const h of game.hazards){h.a+=h.speed*dt;const hx=clamp(h.x+Math.cos(h.a)*Math.min(W,H)*.045,20,W-20),hy=clamp(h.y+Math.sin(h.a)*Math.min(W,H)*.035,35,H-20);for(const c of game.cores)if(c.alive&&Math.hypot(c.x-hx,c.y-hy)<c.r+h.r)hit(c)}if(game.cores.every(c=>!c.alive)){if(game.time>cfgNow.time*.5)award('speed','LIGHTNING');finish(true);return}for(const p of game.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97}game.particles=game.particles.filter(p=>p.life>0);for(const r of game.rings){r.life-=dt;r.r+=130*dt}game.rings=game.rings.filter(r=>r.life>0);for(const f of game.texts){f.life-=dt;f.y-=35*dt}game.texts=game.texts.filter(f=>f.life>0);game.shake=Math.max(0,game.shake-dt);hud()}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(game.shake)ctx.translate(rand(-4,4),rand(-4,4));ctx.strokeStyle='#171d31';ctx.lineWidth=1;for(let x=0;x<W;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}const m=game.magnet,g=ctx.createRadialGradient(m.x,m.y,3,m.x,m.y,105);g.addColorStop(0,'#8ceaff66');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(m.x,m.y,105,0,TAU);ctx.fill();for(const h of game.hazards){const hx=clamp(h.x+Math.cos(h.a)*Math.min(W,H)*.045,20,W-20),hy=clamp(h.y+Math.sin(h.a)*Math.min(W,H)*.035,35,H-20);ctx.save();ctx.translate(hx,hy);ctx.rotate(h.a*2);ctx.shadowBlur=20;ctx.shadowColor='#ff5577';ctx.strokeStyle='#ff5577';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?h.r*.58:h.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.stroke();ctx.restore()}for(const c of game.cores){if(!c.alive)continue;ctx.shadowBlur=20;ctx.shadowColor=color(c.type);ctx.fillStyle=color(c.type);ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#07101b';ctx.beginPath();ctx.arc(c.x-3,c.y-3,3,0,TAU);ctx.fill()}for(const r of game.rings){ctx.globalAlpha=r.life/r.max;ctx.strokeStyle=r.col;ctx.lineWidth=2;ctx.beginPath();ctx.arc(r.x,r.y,r.r,0,TAU);ctx.stroke()}ctx.globalAlpha=1;ctx.shadowBlur=28;ctx.shadowColor='#67dcff';ctx.fillStyle='#ecfbff';ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#4acfff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(m.x,m.y,m.r-3,0,TAU);ctx.stroke();ctx.strokeStyle='#091121';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(m.x-11,m.y);ctx.lineTo(m.x+11,m.y);ctx.stroke();for(const p of game.particles){ctx.globalAlpha=p.life/p.max;ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;for(const f of game.texts){ctx.globalAlpha=f.life/.8;ctx.fillStyle=f.col;ctx.font='900 14px system-ui';ctx.textAlign='center';ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.restore();if(!game.over){ctx.fillStyle='#9aa7c8';ctx.font='900 11px system-ui';ctx.textAlign='right';ctx.fillText(Math.ceil(game.time)+'s',W-18,25)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
function pointer(e){const r=canvas.getBoundingClientRect();game.mouse.x=e.clientX-r.left;game.mouse.y=e.clientY-r.top}
canvas.addEventListener('pointerdown',e=>{if(game.over||game.paused)return;tone(220,.03);pointer(e);game.drag=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{pointer(e);if(game.drag){game.magnet.x=game.mouse.x;game.magnet.y=game.mouse.y}});canvas.addEventListener('pointerup',()=>game.drag=false);canvas.addEventListener('pointercancel',()=>game.drag=false);
function home(){game.paused=true;overlay.classList.remove('hidden');overlayKicker.textContent='MAGNET MAYHEM';overlayTitle.textContent='THE MAGNET NEVER STOPS';overlayText.innerHTML=`<b>1,000 levels</b> · ${save.unlocked} unlocked · ${save.coins} coins<br><br><b>CONTROLS</b><br>Drag anywhere to move the magnet.<br>Double-click for a short Overdrive burst.<br><br><b>ACHIEVEMENTS</b><br>☆ First Pull · ☆ Chain Reaction · ☆ Lightning · ☆ Ten Down · ☆ Century · ☆ Mayhem Master`;primaryBtn.textContent='CONTINUE';secondaryBtn.classList.remove('hidden');secondaryBtn.textContent='LEVEL SELECT';primaryBtn.onclick=()=>{game.paused=false;hide()};secondaryBtn.onclick=levelSelect}
function levelSelect(){overlay.classList.remove('hidden');overlayKicker.textContent='LEVEL SELECT';overlayTitle.textContent='CHOOSE YOUR LEVEL';overlayText.innerHTML=`Highest unlocked: <b>${save.unlocked}</b><br><input id="levelInput" type="number" min="1" max="${save.unlocked}" value="${game.level}" aria-label="Level" style="width:110px;margin:15px auto;padding:12px;border-radius:10px;border:1px solid #394666;background:#0b1020;color:#fff;text-align:center;font-weight:900">`;primaryBtn.textContent='PLAY LEVEL';secondaryBtn.textContent='BACK';secondaryBtn.classList.remove('hidden');primaryBtn.onclick=()=>start(document.getElementById('levelInput')?.value||1);secondaryBtn.onclick=home}
pauseBtn.addEventListener('click',()=>{if(game.over)return;game.paused=!game.paused;if(game.paused){overlay.classList.remove('hidden');overlayKicker.textContent='PAUSED';overlayTitle.textContent='LEVEL '+game.level;overlayText.innerHTML=`Score <b>${Math.floor(game.score)}</b> · Best <b>${best(game.level)}</b>`;primaryBtn.textContent='RESUME';secondaryBtn.classList.add('hidden');primaryBtn.onclick=()=>{game.paused=false;hide()}}else hide()});homeBtn.addEventListener('click',home);muteBtn.addEventListener('click',()=>{mute=!mute;muteBtn.textContent=mute?'SOUND OFF':'SOUND ON';if(!mute)tone(520,.07)});
canvas.addEventListener('dblclick',()=>{if(!game.over&&!game.paused){game.time=Math.min(cfg(game.level).time,game.time+2.5);game.combo=Math.min(12,game.combo+2);showToast('OVERDRIVE  +2.5s');burst(game.magnet.x,game.magnet.y,'#ffffff',30);tone(760,.12,'square')}});
start(1);requestAnimationFrame(loop);
