const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),comboEl=document.getElementById('combo'),levelEl=document.getElementById('level');
const overlay=document.getElementById('overlay'),overlayKicker=document.getElementById('overlayKicker'),overlayTitle=document.getElementById('overlayTitle'),overlayText=document.getElementById('overlayText'),primaryBtn=document.getElementById('primaryBtn'),secondaryBtn=document.getElementById('secondaryBtn'),pauseBtn=document.getElementById('pauseBtn'),toast=document.getElementById('toast');
let W=0,H=0,dpr=1,game=null,last=0;
const TAU=Math.PI*2,MAX_LEVEL=1000,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){dpr=Math.min(2,devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(game){game.magnet.x=W/2;game.magnet.y=H/2}}addEventListener('resize',resize);resize();
function seeded(n){const x=Math.sin(n*999.91)*43758.5453;return x-Math.floor(x)}
function cfg(l){return{cores:Math.min(12,3+Math.floor(l*.018)),hazards:Math.min(9,Math.floor(1+l/3)),time:Math.max(12,30-l*.012)}}
function layout(l){const c=cfg(l),cores=[],hazards=[];for(let i=0;i<c.cores;i++){const q=seeded(l*31+i*17),q2=seeded(l*73+i*29);cores.push({x:(.08+q*.84)*W,y:(.12+q2*.76)*H,r:13,type:['cyan','pink','gold','violet'][(i+l)%4],alive:true,vx:0,vy:0})}for(let i=0;i<c.hazards;i++){const q=seeded(l*101+i*13),q2=seeded(l*149+i*23);hazards.push({x:(.08+q*.84)*W,y:(.12+q2*.76)*H,r:17+seeded(l*211+i)*9,a:seeded(l*271+i)*TAU,speed:.35+seeded(l*313+i)*.9})}return{cores,hazards}}
function boards(){try{return JSON.parse(localStorage.getItem('magnetMayhemBoards')||'{}')}catch{return{}}}function best(l){return boards()[l]||0}function save(l,s){const b=boards();b[l]=Math.max(b[l]||0,Math.floor(s));localStorage.setItem('magnetMayhemBoards',JSON.stringify(b))}
function newGame(level=1){game={level,levelScore:0,combo:1,time:cfg(level).time,cores:[],hazards:[],particles:[],drag:false,paused:false,over:false,won:false,shake:0,magnet:{x:W/2,y:H/2,r:29},mouse:{x:W/2,y:H/2}};spawn();hud()}
function spawn(){const l=layout(game.level);game.cores=l.cores;game.hazards=l.hazards;game.time=cfg(game.level).time;showToast(`LEVEL ${game.level}  •  BEST ${best(game.level)}`)}
function col(t){return{cyan:'#5ce1ff',pink:'#ff69bc',gold:'#ffd66b',violet:'#a98cff'}[t]||'#fff'}
function burst(x,y,c,n=18){for(let i=0;i<n;i++){const a=rand(0,TAU),s=rand(50,210);game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.3,.75),max:.75,col:c,r:rand(1,3)})}}
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1100)}function hud(){scoreEl.textContent=Math.floor(game.levelScore);comboEl.textContent=`x${game.combo}`;levelEl.textContent=game.level}
function stars(){let s=1;if(game.time>cfg(game.level).time*.35)s++;if(game.combo>=5)s++;return Math.min(3,s)}
function finish(win){game.over=true;game.won=win;if(win)save(game.level,game.levelScore);overlay.classList.remove('hidden');overlayKicker.textContent=win?'LEVEL COMPLETE':'RUN OVER';overlayTitle.textContent=win?`LEVEL ${game.level}`:'MAGNET JAM';const st=stars();overlayText.textContent=win?`Score ${Math.floor(game.levelScore)}  •  ${'★'.repeat(st)}${'☆'.repeat(3-st)}  •  Best ${best(game.level)}`:'Time or hazards ended the run. Try the level again.';primaryBtn.textContent=win?(game.level<MAX_LEVEL?'NEXT LEVEL':'ALL 1,000 LEVELS COMPLETE'):'TRY AGAIN';secondaryBtn.classList.toggle('hidden',!win);if(win)secondaryBtn.textContent='REPLAY LEVEL'}
function update(dt){if(game.paused||game.over)return;game.time-=dt;if(game.time<=0){finish(false);return}const m=game.magnet;for(const c of game.cores){if(!c.alive)continue;const dx=m.x-c.x,dy=m.y-c.y,d=Math.hypot(dx,dy)||1,pull=game.drag?Math.min(1250,100000/(d*d+160)):0;c.vx+=(dx/d)*pull*dt;c.vy+=(dy/d)*pull*dt;c.vx*=Math.pow(.035,dt);c.vy*=Math.pow(.035,dt);c.x=clamp(c.x+c.vx*dt,c.r,W-c.r);c.y=clamp(c.y+c.vy*dt,c.r,H-c.r);if(d<m.r+c.r+8){c.alive=false;const gained=100*game.combo+Math.floor(game.time*4);game.levelScore+=gained;game.combo=Math.min(12,game.combo+1);burst(c.x,c.y,col(c.type),22);showToast(`+${gained}   COMBO x${game.combo}`)}}for(const h of game.hazards){h.a+=h.speed*dt;for(const c of game.cores)if(c.alive&&dist(c,h)<c.r+h.r){game.combo=1;game.levelScore=Math.max(0,game.levelScore-75);burst(c.x,c.y,'#ff5577',24);c.x=rand(35,W-35);c.y=rand(35,H-35);c.vx=c.vy=0;game.shake=.25}}if(game.cores.every(c=>!c.alive)){game.levelScore+=Math.floor(game.time*20);finish(true)}for(const p of game.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97}game.particles=game.particles.filter(p=>p.life>0);game.shake=Math.max(0,game.shake-dt);hud()}
function grid(){ctx.strokeStyle='#171d31';ctx.lineWidth=1;for(let x=0;x<W;x+=42){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=42){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(game.shake)ctx.translate(rand(-4,4),rand(-4,4));grid();const m=game.magnet,g=ctx.createRadialGradient(m.x,m.y,3,m.x,m.y,95);g.addColorStop(0,'#8ceaff55');g.addColorStop(1,'transparent');ctx.fillStyle=g;ctx.beginPath();ctx.arc(m.x,m.y,95,0,TAU);ctx.fill();for(const h of game.hazards){ctx.save();ctx.translate(h.x,h.y);ctx.rotate(h.a);ctx.shadowBlur=20;ctx.shadowColor='#ff5577';ctx.strokeStyle='#ff5577';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?h.r*.58:h.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.stroke();ctx.restore()}for(const c of game.cores){if(!c.alive)continue;ctx.shadowBlur=20;ctx.shadowColor=col(c.type);ctx.fillStyle=col(c.type);ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#07101b';ctx.beginPath();ctx.arc(c.x-3,c.y-3,3,0,TAU);ctx.fill()}ctx.shadowBlur=28;ctx.shadowColor='#67dcff';ctx.fillStyle='#ecfbff';ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#4acfff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(m.x,m.y,m.r-3,0,TAU);ctx.stroke();ctx.strokeStyle='#091121';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(m.x-11,m.y);ctx.lineTo(m.x+11,m.y);ctx.stroke();for(const p of game.particles){ctx.globalAlpha=p.life/p.max;ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;ctx.restore();if(!game.over){ctx.fillStyle='#7885a5';ctx.font='800 11px system-ui';ctx.textAlign='right';ctx.fillText(`${Math.ceil(game.time)}s`,W-18,25)}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
function pointer(e){const r=canvas.getBoundingClientRect();game.mouse.x=e.clientX-r.left;game.mouse.y=e.clientY-r.top}
canvas.addEventListener('pointerdown',e=>{if(game.over||game.paused)return;pointer(e);game.drag=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{pointer(e);if(game.drag){game.magnet.x=game.mouse.x;game.magnet.y=game.mouse.y}});canvas.addEventListener('pointerup',()=>game.drag=false);canvas.addEventListener('pointercancel',()=>game.drag=false);
pauseBtn.onclick=()=>{if(game.over)return;game.paused=!game.paused;overlay.classList.toggle('hidden',!game.paused);if(game.paused){overlayKicker.textContent='PAUSED';overlayTitle.textContent=`LEVEL ${game.level}`;overlayText.textContent=`Score ${Math.floor(game.levelScore)}  •  Personal best ${best(game.level)}`;primaryBtn.textContent='RESUME';secondaryBtn.classList.add('hidden')}};
primaryBtn.onclick=()=>{if(!game.over){game.paused=false;overlay.classList.add('hidden');return}if(game.won&&game.level<MAX_LEVEL)newGame(game.level+1);else newGame(game.level)};secondaryBtn.onclick=()=>newGame(game.level);
newGame(1);requestAnimationFrame(loop);
