const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const scoreEl=document.getElementById('score'),comboEl=document.getElementById('combo'),levelEl=document.getElementById('level');
const overlay=document.getElementById('overlay'),overlayKicker=document.getElementById('overlayKicker'),overlayTitle=document.getElementById('overlayTitle'),overlayText=document.getElementById('overlayText'),primaryBtn=document.getElementById('primaryBtn'),secondaryBtn=document.getElementById('secondaryBtn'),pauseBtn=document.getElementById('pauseBtn'),toast=document.getElementById('toast');
let W=0,H=0,dpr=1,game=null,last=0,raf=0;
const TAU=Math.PI*2;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)); const rand=(a,b)=>a+Math.random()*(b-a); const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
function resize(){dpr=Math.min(2,devicePixelRatio||1);W=canvas.clientWidth;H=canvas.clientHeight;canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);if(game)game.magnet={x:W/2,y:H/2,r:28}}
addEventListener('resize',resize);resize();
function levelConfig(l){return{cores:Math.min(7,3+Math.floor((l-1)*.65)),hazards:Math.min(6,Math.floor((l+1)/2)),speed:55+l*7,time:Math.max(16,29-l*.7)}}
function newGame(level=1){let c=levelConfig(level);game={level,score:0,total:0,combo:1,time:c.time,cores:[],hazards:[],particles:[],drag:false,paused:false,over:false,won:false,shake:0,magnet:{x:W/2,y:H/2,r:28},mouse:{x:W/2,y:H/2}};spawnLevel();updateHUD()}
function safePoint(){let p={x:rand(45,W-45),y:rand(45,H-45)};for(let i=0;i<30;i++){if(Math.hypot(p.x-W/2,p.y-H/2)>Math.min(W,H)*.22)return p;p={x:rand(45,W-45),y:rand(45,H-45)}}return p}
function spawnLevel(){const c=levelConfig(game.level);game.cores=[];game.hazards=[];for(let i=0;i<c.cores;i++){let p=safePoint(),types=['cyan','pink','gold'];game.cores.push({x:p.x,y:p.y,r:13,type:types[i%types.length],vx:0,vy:0,alive:true})}for(let i=0;i<c.hazards;i++){let p=safePoint();game.hazards.push({x:p.x,y:p.y,r:rand(17,25),a:rand(0,TAU),speed:rand(.4,1.1)})}game.time=c.time;game.total=game.cores.length;showToast(`LEVEL ${game.level}`)}
function color(type){return type==='cyan'?'#5ce1ff':type==='pink'?'#ff69bc':'#ffd66b'}
function burst(x,y,col,n=14){for(let i=0;i<n;i++){let a=rand(0,TAU),s=rand(45,190);game.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.35,.75),max:.75,col,r:rand(1,3)})}}
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('show'),1100)}
function updateHUD(){scoreEl.textContent=Math.floor(game.score);comboEl.textContent=`x${game.combo}`;levelEl.textContent=game.level}
function finish(win){game.over=true;game.won=win;overlay.classList.remove('hidden');overlayKicker.textContent=win?'LEVEL CLEAR':'RUN OVER';overlayTitle.textContent=win?'MAGNET MAYHEM':'MAGNET JAM';overlayText.textContent=win?`Level ${game.level} cleared. Score: ${Math.floor(game.score)}.`:'The hazards got you. Keep the combo alive.';primaryBtn.textContent=win?'NEXT LEVEL':'TRY AGAIN';secondaryBtn.classList.toggle('hidden',!win);if(win){secondaryBtn.textContent='REPLAY LEVEL'}}
function update(dt){if(game.paused||game.over)return;game.time-=dt;if(game.time<=0){finish(false);return}const m=game.magnet;for(const c of game.cores){if(!c.alive)continue;let dx=m.x-c.x,dy=m.y-c.y,d=Math.hypot(dx,dy)||1;let pull=game.drag?Math.min(1200,90000/(d*d+180)):0;c.vx+=(dx/d)*pull*dt;c.vy+=(dy/d)*pull*dt;c.vx*=Math.pow(.035,dt);c.vy*=Math.pow(.035,dt);c.x+=c.vx*dt;c.y+=c.vy*dt;c.x=clamp(c.x,c.r,W-c.r);c.y=clamp(c.y,c.r,H-c.r);if(d<m.r+c.r+7){c.alive=false;game.score+=100*game.combo;game.combo=Math.min(12,game.combo+1);burst(c.x,c.y,color(c.type),20);showToast(`+${100*(game.combo-1)}  COMBO x${game.combo}`)}}for(const h of game.hazards){h.a+=h.speed*dt;for(const c of game.cores)if(c.alive&&dist(c,h)<c.r+h.r){game.combo=1;game.score=Math.max(0,game.score-60);burst(c.x,c.y,'#ff5577',22);c.x=rand(40,W-40);c.y=rand(40,H-40);c.vx=c.vy=0;game.shake=.25}}if(game.cores.every(c=>!c.alive)){game.level++;game.score+=500*game.level;game.paused=true;finish(true);game.paused=false}for(const p of game.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97}game.particles=game.particles.filter(p=>p.life>0);game.shake=Math.max(0,game.shake-dt);updateHUD()}
function grid(){ctx.strokeStyle='#171d31';ctx.lineWidth=1;let step=42;for(let x=0;x<W;x+=step){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=step){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}}
function draw(){ctx.clearRect(0,0,W,H);ctx.save();if(game.shake)ctx.translate(rand(-4,4),rand(-4,4));grid();const m=game.magnet;let glow=ctx.createRadialGradient(m.x,m.y,4,m.x,m.y,80);glow.addColorStop(0,'#8ceaff55');glow.addColorStop(1,'transparent');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(m.x,m.y,80,0,TAU);ctx.fill();for(const h of game.hazards){ctx.save();ctx.translate(h.x,h.y);ctx.rotate(h.a);ctx.shadowBlur=18;ctx.shadowColor='#ff5577';ctx.strokeStyle='#ff5577';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<8;i++){let a=i*Math.PI/4,r=i%2?h.r*.65:h.r;ctx.lineTo(Math.cos(a)*r,Math.sin(a)*r)}ctx.closePath();ctx.stroke();ctx.restore()}for(const c of game.cores){if(!c.alive)continue;ctx.shadowBlur=18;ctx.shadowColor=color(c.type);ctx.fillStyle=color(c.type);ctx.beginPath();ctx.arc(c.x,c.y,c.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#07101b';ctx.beginPath();ctx.arc(c.x-3,c.y-3,3,0,TAU);ctx.fill()}ctx.shadowBlur=25;ctx.shadowColor='#67dcff';ctx.fillStyle='#ecfbff';ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,TAU);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#4acfff';ctx.lineWidth=5;ctx.beginPath();ctx.arc(m.x,m.y,m.r-3,0,TAU);ctx.stroke();ctx.strokeStyle='#091121';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(m.x-11,m.y);ctx.lineTo(m.x+11,m.y);ctx.stroke();for(const p of game.particles){ctx.globalAlpha=p.life/p.max;ctx.fillStyle=p.col;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,TAU);ctx.fill()}ctx.globalAlpha=1;ctx.restore();if(!game.over){ctx.fillStyle='#7885a5';ctx.font='800 11px system-ui';ctx.textAlign='right';ctx.fillText(`${Math.ceil(game.time)}s`,W-18,25)}}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();raf=requestAnimationFrame(loop)}
function pointer(e){let r=canvas.getBoundingClientRect();game.mouse.x=e.clientX-r.left;game.mouse.y=e.clientY-r.top}
canvas.addEventListener('pointerdown',e=>{pointer(e);game.drag=true;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{pointer(e);if(game.drag){game.magnet.x=game.mouse.x;game.magnet.y=game.mouse.y}});canvas.addEventListener('pointerup',e=>{game.drag=false});
pauseBtn.onclick=()=>{if(game.over)return;game.paused=!game.paused;overlay.classList.toggle('hidden',!game.paused);overlayKicker.textContent='PAUSED';overlayTitle.textContent='MAGNET MAYHEM';overlayText.textContent='Take a breath. The cores are waiting.';primaryBtn.textContent='RESUME';secondaryBtn.classList.add('hidden')};
primaryBtn.onclick=()=>{if(game.over){if(game.won){newGame(game.level)}else newGame(game.level)}else{game.paused=false;overlay.classList.add('hidden')}};
secondaryBtn.onclick=()=>{newGame(game.level)};
newGame(1);raf=requestAnimationFrame(loop);
