(()=>{
'use strict';
const C=document.getElementById('game'),X=C.getContext('2d'),$=id=>document.getElementById(id);
const scoreEl=$('score'),comboEl=$('combo'),levelEl=$('level'),overlay=$('overlay'),ok=$('overlayKicker'),ot=$('overlayTitle'),ox=$('overlayText'),primary=$('primaryBtn'),secondary=$('secondaryBtn'),pauseBtn=$('pauseBtn'),muteBtn=$('muteBtn'),toast=$('toast');
const KEY='magnetMayhemSave';
const DEFAULT={unlocked:1,best:{},coins:0,up:{power:0,time:0,shield:0,score:0},stats:{wins:0,cores:0},medals:[]};
let S=load(),W=1,H=1,D=1,g=null,keys={},muted=false,audio=null;
function load(){try{const s=JSON.parse(localStorage.getItem(KEY)||'{}');return {...DEFAULT,...s,up:{...DEFAULT.up,...s.up},stats:{...DEFAULT.stats,...s.stats},best:s.best||{},medals:s.medals||[]}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),TAU=Math.PI*2;
function resize(){D=Math.min(2,devicePixelRatio||1);W=C.clientWidth||innerWidth;H=C.clientHeight||innerHeight;C.width=W*D;C.height=H*D;X.setTransform(D,0,0,D,0,0)}
addEventListener('resize',resize);resize();
function beep(f=440,d=.06,type='sine'){if(muted)return;if(!audio)try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch{return}if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),q=audio.createGain();o.type=type;o.frequency.value=f;q.gain.value=.025;q.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(q);q.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function msg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove('show'),1300)}
function cfg(n){const boss=n%10===0;return{boss,cores:Math.min(24,4+Math.floor((n-1)/18)+(boss?3:0)),hazards:Math.min(16,1+Math.floor((n-1)/25)+(boss?2:0)),time:Math.max(11,32-n*.012+S.up.time*1.7),speed:1+Math.floor((n-1)/15)*.1}}
function point(list,gap){for(let i=0;i<120;i++){const p={x:rand(42,W-42),y:rand(35,H-42)};if(Math.hypot(p.x-W/2,p.y-H/2)>Math.min(W,H)*.2&&!list.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<gap)){list.push(p);return p}}return{x:rand(45,W-45),y:rand(45,H-45)}}
function makeLevel(n){const z=cfg(n),used=[],cores=[],hazards=[];for(let i=0;i<z.cores;i++){const p=point(used,48);cores.push({x:p.x,y:p.y,r:i%6===0?15:12,type:i%5,phase:rand(0,TAU),vx:0,vy:0,alive:true,born:0})}for(let i=0;i<z.hazards;i++){const p=point(used,72);hazards.push({x:p.x,y:p.y,r:rand(14,23),orbit:rand(22,72),phase:rand(0,TAU),a:rand(0,TAU),speed:rand(.55,1.05)*z.speed})}return{cores,hazards}}
function start(n=1){n=clamp(Math.floor(n)||1,1,Math.max(1,S.unlocked));const z=cfg(n),l=makeLevel(n);g={n,score:0,combo:1,time:z.time,elapsed:0,cores:l.cores,hazards:l.hazards,m:{x:W/2,y:H/2,r:28},drag:false,paused:false,ended:false,shield:S.up.shield>0,freeze:0,overdrive:0,powers:[],particles:[],rings:[],floats:[],spawn:6,boss:{x:W/2,y:80,r:z.boss?36:0,a:0}};hide();hud();msg(z.boss?'BOSS LEVEL '+n:'LEVEL '+n);beep(300,.05)}
function hud(){if(!g)return;scoreEl.textContent=Math.floor(g.score).toLocaleString();comboEl.textContent='x'+g.combo;levelEl.textContent=g.n}
function hide(){overlay.classList.add('hidden')}
function modal(k,title,text,label='CONTINUE',secondLabel='MENU',secondFn=()=>window.openMainMenu?.()){g.paused=true;ok.textContent=k;ot.textContent=title;ox.innerHTML=text;primary.textContent=label;primary.onclick=()=>{hide();g.paused=false};secondary.textContent=secondLabel;secondary.classList.remove('hidden');secondary.onclick=secondFn;overlay.classList.remove('hidden')}
function burst(x,y,kind,n=20){for(let i=0;i<n;i++){const a=rand(0,TAU),s=rand(60,260);g.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:rand(.3,.75),kind})}}
function medal(id,name){if(S.medals.includes(id))return;S.medals.push(id);save();msg('MEDAL • '+name);beep(880,.12,'triangle')}
function collect(c){c.alive=false;const age=Math.max(0,g.elapsed-c.born);const speed=Math.max(0,260-Math.floor(age*55));const gain=Math.floor((70+speed)*(1+S.up.score*.1)*g.combo*(g.overdrive?2:1));g.score+=gain;g.combo=Math.min(15,g.combo+1);S.stats.cores++;g.rings.push({x:c.x,y:c.y,r:4,life:.5,type:c.type});g.floats.push({x:c.x,y:c.y,text:'+'+gain,life:.85,type:c.type});burst(c.x,c.y,c.type,24);beep(240+g.combo*38,.045);if(S.stats.cores===1)medal('first','FIRST PULL');if(g.combo>=8)medal('chain','CHAIN REACTION')}
function damage(c){if(S.up.power>0&&Math.random()<Math.min(.5,S.up.power*.08)){g.combo=Math.max(1,g.combo-1);return}if(g.shield){g.shield=false;burst(c.x,c.y,4,30);msg('SHIELD BROKEN');beep(110,.1,'square');return}g.score=Math.max(0,g.score-120);g.combo=1;g.shake=.25;c.x=rand(35,W-35);c.y=rand(45,H-45);c.vx=c.vy=0;burst(c.x,c.y,4,18);beep(75,.1,'sawtooth')}
function spawnPower(){const types=['TIME','FREEZE','SHIELD','2X'];g.powers.push({type:types[Math.floor(Math.random()*4)],x:rand(55,W-55),y:rand(60,H-55),r:14,life:11,a:0})}
function finish(win){g.ended=true;g.drag=false;if(!win){modal('TIME OUT','MAGNET JAM',`LEVEL <b>${g.n}</b><br>SCORE <b>${Math.floor(g.score).toLocaleString()}</b> · BEST <b>${S.best[g.n]||0}</b><br><br>Get the cores faster to build a higher score.`,'RETRY','MENU');primary.onclick=()=>start(g.n);return}const stars=g.time>cfg(g.n).time*.5?3:g.time>cfg(g.n).time*.23?2:1;const timeBonus=Math.floor(g.time*35)+stars*100;g.score+=timeBonus;const final=Math.floor(g.score),old=S.best[g.n]||0;S.best[g.n]=Math.max(old,final);S.unlocked=Math.max(S.unlocked,Math.min(1000,g.n+1));S.coins+=stars;S.stats.wins++;if(g.n%10===0)medal('boss'+g.n,'BOSS CRUSH');if(g.n>=10)medal('ten','TEN DOWN');if(g.n>=100)medal('century','CENTURY');if(g.n===1000)medal('master','MAYHEM MASTER');save();modal(cfg(g.n).boss?'BOSS DEFEATED':'LEVEL COMPLETE','LEVEL '+g.n,`SCORE <b>${final.toLocaleString()}</b><br>${'★'.repeat(stars)}${'☆'.repeat(3-stars)} &nbsp; TIME BONUS <b>+${timeBonus}</b><br>BEST <b>${S.best[g.n].toLocaleString()}</b> · COINS <b>+${stars}</b>${final>old?'<br><strong>NEW HIGH SCORE</strong>':''}`,g.n<1000?'NEXT LEVEL':'PLAY AGAIN','REPLAY',()=>start(g.n));primary.onclick=()=>start(g.n<1000?g.n+1:g.n)}
function update(dt){if(!g||g.paused||g.ended)return;const z=cfg(g.n);g.elapsed+=dt;g.time-=dt;if(g.time<=0){finish(false);return}if(g.freeze>0)g.freeze-=dt;if(g.overdrive>0)g.overdrive-=dt;g.spawn-=dt;if(g.spawn<=0&&g.powers.length<2){spawnPower();g.spawn=rand(7,11)}let mx=(keys.ArrowRight||keys.d||keys.D?1:0)-(keys.ArrowLeft||keys.a||keys.A?1:0),my=(keys.ArrowDown||keys.s||keys.S?1:0)-(keys.ArrowUp||keys.w||keys.W?1:0);if(mx||my){const l=Math.hypot(mx,my);g.m.x=clamp(g.m.x+mx/l*440*dt,20,W-20);g.m.y=clamp(g.m.y+my/l*440*dt,20,H-20);g.drag=true}
for(const c of g.cores){if(!c.alive)continue;c.born=c.born||g.elapsed;const dx=g.m.x-c.x,dy=g.m.y-c.y,d=Math.hypot(dx,dy)||1;if(g.drag){const pull=(175000/(d*d+180))*(1+S.up.power*.25);c.vx+=dx/d*pull*dt;c.vy+=dy/d*pull*dt}c.vx*=Math.pow(.03,dt);c.vy*=Math.pow(.03,dt);c.x=clamp(c.x+c.vx*dt,c.r,W-c.r);c.y=clamp(c.y+c.vy*dt,c.r,H-c.r);c.phase+=dt*4;if(d<g.m.r+c.r+10)collect(c)}
for(const h of g.hazards){h.a+=h.speed*dt*(g.freeze>0?.1:1);const hx=h.x+Math.cos(h.a+h.phase)*h.orbit,hy=h.y+Math.sin(h.a+h.phase)*h.orbit*.72;for(const c of g.cores)if(c.alive&&Math.hypot(c.x-hx,c.y-hy)<c.r+h.r)damage(c)}
if(z.boss){g.boss.a+=dt*.7;g.boss.x=W/2+Math.cos(g.boss.a)*Math.min(W*.32,180);g.boss.y=H*.25+Math.sin(g.boss.a*1.35)*90;for(const c of g.cores)if(c.alive&&Math.hypot(c.x-g.boss.x,c.y-g.boss.y)<c.r+g.boss.r)damage(c)}
for(const p of g.powers){p.life-=dt;p.a+=dt*4;if(p.life<=0)continue;if(Math.hypot(p.x-g.m.x,p.y-g.m.y)<p.r+g.m.r){if(p.type==='TIME')g.time=Math.min(z.time+6,g.time+6);if(p.type==='FREEZE')g.freeze=5;if(p.type==='SHIELD')g.shield=true;if(p.type==='2X')g.overdrive=5;msg(p.type+'!');burst(p.x,p.y,2,30);beep(760,.09,'square');p.life=0}}g.powers=g.powers.filter(p=>p.life>0);if(g.cores.every(c=>!c.alive)){finish(true);return}
for(const p of g.particles){p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.965;p.vy*=.965}g.particles=g.particles.filter(p=>p.life>0);for(const r of g.rings){r.life-=dt;r.r+=150*dt}g.rings=g.rings.filter(r=>r.life>0);for(const f of g.floats){f.life-=dt;f.y-=35*dt}g.floats=g.floats.filter(f=>f.life>0);hud()}
function draw(){X.clearRect(0,0,W,H);X.fillStyle='#050711';X.fillRect(0,0,W,H);X.strokeStyle='#121a2b';X.lineWidth=1;for(let x=0;x<W;x+=42){X.beginPath();X.moveTo(x,0);X.lineTo(x,H);X.stroke()}for(let y=0;y<H;y+=42){X.beginPath();X.moveTo(0,y);X.lineTo(W,y);X.stroke()}if(!g)return;X.save();if(g.shake)X.translate(rand(-5,5),rand(-5,5));
for(const h of g.hazards){const x=h.x+Math.cos(h.a+h.phase)*h.orbit,y=h.y+Math.sin(h.a+h.phase)*h.orbit*.72;X.save();X.translate(x,y);X.rotate(h.a*2);X.shadowBlur=20;X.shadowColor='#ff5577';X.strokeStyle='#ff5577';X.lineWidth=3;X.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?h.r*.48:h.r;X.lineTo(Math.cos(a)*r,Math.sin(a)*r)}X.closePath();X.stroke();X.restore()}
if(cfg(g.n).boss){X.shadowBlur=30;X.shadowColor='#ff5577';X.strokeStyle='#ff5577';X.lineWidth=4;X.beginPath();X.arc(g.boss.x,g.boss.y,g.boss.r+Math.sin(g.boss.a*6)*3,0,TAU);X.stroke();X.shadowBlur=0}
for(const p of g.powers){const c=p.type==='TIME'?'#ffd45f':p.type==='FREEZE'?'#58e6ff':p.type==='SHIELD'?'#a98cff':'#ff63b8';X.save();X.translate(p.x,p.y);X.rotate(p.a);X.shadowBlur=20;X.shadowColor=c;X.strokeStyle=c;X.lineWidth=3;X.beginPath();X.arc(0,0,p.r,0,TAU);X.stroke();X.shadowBlur=0;X.fillStyle=c;X.font='900 10px system-ui';X.textAlign='center';X.textBaseline='middle';X.fillText(p.type==='2X'?'2X':p.type[0],0,0);X.restore()}
const cols=['#58e6ff','#ff63b8','#ffd45f','#a98cff','#7df5a1'];for(const c of g.cores)if(c.alive){const col=cols[c.type];X.shadowBlur=24;X.shadowColor=col;X.fillStyle=col;X.beginPath();X.arc(c.x,c.y,c.r+Math.sin(c.phase)*1.5,0,TAU);X.fill();X.shadowBlur=0;X.fillStyle='#fff';X.globalAlpha=.8;X.beginPath();X.arc(c.x-c.r*.3,c.y-c.r*.3,c.r*.25,0,TAU);X.fill();X.globalAlpha=1}
for(const r of g.rings){X.globalAlpha=Math.max(0,r.life*2);X.strokeStyle=cols[r.type];X.lineWidth=3;X.beginPath();X.arc(r.x,r.y,r.r,0,TAU);X.stroke();X.globalAlpha=1}for(const p of g.particles){X.globalAlpha=Math.max(0,p.life);X.fillStyle=cols[p.kind]||'#fff';X.fillRect(p.x,p.y,p.life*3,p.life*3);X.globalAlpha=1}for(const f of g.floats){X.globalAlpha=Math.min(1,f.life*2);X.fillStyle=cols[f.type]||'#fff';X.font='900 13px system-ui';X.textAlign='center';X.fillText(f.text,f.x,f.y);X.globalAlpha=1}
const m=g.m;X.shadowBlur=32;X.shadowColor='#d9fbff';X.strokeStyle='#e8fbff';X.lineWidth=4;X.beginPath();X.arc(m.x,m.y,m.r,0,TAU);X.stroke();X.shadowBlur=12;X.strokeStyle='#58e6ff';X.lineWidth=7;X.beginPath();X.arc(m.x,m.y,m.r-7,0,TAU);X.stroke();X.shadowBlur=0;X.fillStyle='#07111d';X.beginPath();X.arc(m.x,m.y,10,0,TAU);X.fill();X.strokeStyle='#fff';X.lineWidth=2;X.stroke();if(g.shield){X.strokeStyle='#a98cff';X.lineWidth=3;X.beginPath();X.arc(m.x,m.y,m.r+9,0,TAU);X.stroke()}if(g.overdrive){X.strokeStyle='#ff63b8';X.lineWidth=3;X.beginPath();X.arc(m.x,m.y,m.r+14,0,TAU);X.stroke()}X.restore()}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
C.addEventListener('pointerdown',e=>{if(!g||g.paused)return;g.drag=true;C.setPointerCapture?.(e.pointerId);move(e)});C.addEventListener('pointermove',move);C.addEventListener('pointerup',e=>{g&&(g.drag=false);C.releasePointerCapture?.(e.pointerId)});function move(e){if(!g||!g.drag)return;const r=C.getBoundingClientRect();g.m.x=clamp(e.clientX-r.left,20,W-20);g.m.y=clamp(e.clientY-r.top,20,H-20)}
addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='o'||e.key==='O'){if(g&&!g.paused&&!g.ended)g.overdrive=5}if(e.key==='Escape'&&g&&!g.ended){g.paused=!g.paused;if(g.paused)modal('PAUSED','MAGNET MAYHEM','Take a breath. The field is frozen.','RESUME','MENU')}if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault()});addEventListener('keyup',e=>keys[e.key]=false);
pauseBtn.onclick=()=>{if(!g)return;g.paused=!g.paused;if(g.paused)modal('PAUSED','MAGNET MAYHEM','The field is frozen.','RESUME','MENU')};muteBtn.onclick=()=>{muted=!muted;muteBtn.textContent=muted?'SOUND OFF':'SOUND ON'};
window.start=start;window.getSave=()=>S;window.openGameMenu=()=>window.openMainMenu?.();
start(1);
})();