const C=document.getElementById('game'),X=C.getContext('2d');
const scoreEl=document.getElementById('score'),comboEl=document.getElementById('combo'),levelEl=document.getElementById('level'),overlay=document.getElementById('overlay'),ok=document.getElementById('overlayKicker'),ot=document.getElementById('overlayTitle'),ox=document.getElementById('overlayText'),primary=document.getElementById('primaryBtn'),secondary=document.getElementById('secondaryBtn'),pauseBtn=document.getElementById('pauseBtn'),homeBtn=document.getElementById('homeBtn'),muteBtn=document.getElementById('muteBtn'),toast=document.getElementById('toast');
const KEY='magnetMayhemSave',MAX=1000,TAU=Math.PI*2,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),rand=(a,b)=>a+Math.random()*(b-a),COL=['#58e6ff','#ff63b8','#ffd45f','#a98cff','#7df5a1'];
const defaults={unlocked:1,best:{},coins:0,ach:[],up:{pull:0,time:0,shield:0,core:0,stability:0},stats:{wins:0,stars:0},challengeBest:{},challengeDone:{},challengeStreak:0};
let S=load(),W=1,H=1,D=1,g=null,last=0,audio=null,muted=false,keys={},activeChallenge=null;
function load(){try{return Object.assign({},defaults,JSON.parse(localStorage.getItem(KEY)||'{}'),{up:Object.assign({},defaults.up,JSON.parse(localStorage.getItem(KEY)||'{}').up||{}),stats:Object.assign({},defaults.stats,JSON.parse(localStorage.getItem(KEY)||'{}').stats||{})})}catch{return JSON.parse(JSON.stringify(defaults))}}
function save(){localStorage.setItem(KEY,JSON.stringify(S))}
function resize(){D=Math.min(2,devicePixelRatio||1);W=C.clientWidth||innerWidth;H=C.clientHeight||innerHeight;C.width=W*D;C.height=H*D;X.setTransform(D,0,0,D,0,0);if(g&&g.m){g.m.x=clamp(g.m.x,20,W-20);g.m.y=clamp(g.m.y,20,H-20)}}
addEventListener('resize',resize);resize();
function msg(t){toast.textContent=t;toast.classList.add('show');clearTimeout(msg.t);msg.t=setTimeout(()=>toast.classList.remove('show'),1400)}
function beep(f=440,d=.06,type='sine'){if(muted)return;if(!audio)try{audio=new(window.AudioContext||window.webkitAudioContext)()}catch{return}if(audio.state==='suspended')audio.resume();const o=audio.createOscillator(),q=audio.createGain();o.type=type;o.frequency.value=f;q.gain.value=.035;q.gain.exponentialRampToValueAtTime(.001,audio.currentTime+d);o.connect(q);q.connect(audio.destination);o.start();o.stop(audio.currentTime+d)}
function award(id,text){if(S.ach.includes(id))return;S.ach.push(id);save();msg('MEDAL • '+text);beep(900,.12,'triangle')}
function cfg(n){const boss=n%10===0;return{boss,cores:Math.min(18,3+Math.floor((n-1)/22)+(boss?2:0)),hazards:Math.min(13,1+Math.floor(n/28)+(boss?2:0)),time:Math.max(10,31-n*.012+S.up.time*1.6),speed:1+Math.floor((n-1)/16)*.11}}
function point(used,gap){for(let i=0;i<100;i++){const p={x:rand(35,W-35),y:rand(55,H-35)};if(Math.hypot(p.x-W/2,p.y-H/2)>Math.min(W,H)*.16&&!used.some(q=>Math.hypot(q.x-p.x,q.y-p.y)<gap)){used.push(p);return p}}return{x:rand(40,W-40),y:rand(60,H-40)}}
function buildLevel(n){const z=cfg(n),used=[],cores=[],hazards=[];for(let i=0;i<z.cores;i++){const p=point(used,45);cores.push({x:p.x,y:p.y,r:i%7===0?15:12,vx:0,vy:0,type:(i+n)%COL.length,phase:rand(0,TAU),alive:true,spawned:0})}for(let i=0;i<z.hazards;i++){const p=point(used,65);hazards.push({x:p.x,y:p.y,r:rand(14,24),a:rand(0,TAU),phase:rand(0,TAU),orbit:rand(25,70),speed:rand(.55,1.15)*z.speed})}return{cores,hazards}}
function start(n=1){n=clamp(Math.floor(Number(n)||1),1,Math.max(1,S.unlocked));const z=cfg(n),l=buildLevel(n);g={n,score:0,combo:1,time:z.time,elapsed:0,cores:l.cores,hazards:l.hazards,m:{x:W/2,y:H/2,r:30},drag:false,paused:false,over:false,shield:S.up.shield?1:0,freeze:0,overdrive:0,spawn:5,parts:[],rings:[],floats:[],powers:[],shake:0,boss:{x:W/2,y:80,r:z.boss?34:0,a:0}};activeChallenge=window.magnetChallengeActive||null;hideOverlay();hud();msg(z.boss?'BOSS LEVEL '+n:'LEVEL '+n)}
function hud(){if(!g)return;scoreEl.textContent=Math.floor(g.score).toLocaleString();comboEl.textContent='x'+g.combo;levelEl.textContent=g.n}
function hideOverlay(){overlay.classList.add('hidden')}
function showOverlay(k,t,html,p,second,secondFn){g.paused=true;g.over=second==='over'?true:g.over;overlay.classList.remove('hidden');ok.textContent=k;ot.textContent=t;ox.innerHTML=html;primary.textContent=p;primary.onclick=()=>{hideOverlay();if(typeof window.resumeGame==='function')window.resumeGame();else if(g)g.paused=false};secondary.classList.toggle('hidden',!second);if(second){secondary.textContent=second;secondary.onclick=secondFn}}
function particle(x,y,c,n=18){for(let i=0;i<n;i++){const a=rand(0,TAU),s=rand(45,230);g.parts.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,l:rand(.3,.8),m:.8,c,r:rand(1,3)})}}
function pull(c){c.alive=false;const age=Math.max(0,g.elapsed-c.spawned),speedBonus=Math.max(0,240-Math.floor(age*45)),coreBonus=1+S.up.core*.08;let gain=Math.floor((85+speedBonus)*g.combo*coreBonus);if(g.overdrive>0)gain*=2;g.score+=gain;g.combo=Math.min(15,g.combo+1);g.rings.push({x:c.x,y:c.y,r:5,l:.5,m:.5,c:COL[c.type]});g.floats.push({x:c.x,y:c.y,t:'+'+gain,l:.9,c:COL[c.type]});particle(c.x,c.y,COL[c.type],25);beep(260+g.combo*42,.05);award('first','FIRST PULL');if(g.combo>=8)award('combo','CHAIN REACTION')}
function hit(c){if(S.up.stability>0&&Math.random()<Math.min(.45,S.up.stability*.07)){g.combo=Math.max(1,g.combo-1);return}if(g.shield){g.shield=0;particle(c.x,c.y,'#fff',30);msg('SHIELD BROKEN');beep(140,.12,'square');return}g.score=Math.max(0,g.score-100);g.combo=1;g.shake=.25;c.x=rand(30,W-30);c.y=rand(50,H-30);c.vx=c.vy=0;particle(c.x,c.y,'#ff5577',25);beep(80,.12,'sawtooth')}
function spawnPower(){const types=['time','freeze','shield','overdrive'];g.powers.push({type:types[Math.floor(Math.random()*types.length)],x:rand(50,W-50),y:rand(70,H-50),r:13,l:10,a:0})}
function finish(win){g.over=true;g.drag=false;if(!win){showOverlay('RUN OVER','MAGNET JAM',`LEVEL <b>${g.n}</b><br>SCORE <b>${Math.floor(g.score).toLocaleString()}</b> · BEST <b>${S.best[g.n]||0}</b><br><br>Pull the cores faster and keep them clear of hazards.`,'TRY AGAIN','MENU',()=>{hideOverlay();window.openMainMenu&&window.openMainMenu()});primary.onclick=()=>start(g.n);return}const z=cfg(g.n),speedStars=g.time>z.time*.48?3:g.time>z.time*.22?2:1,bonus=Math.floor(g.time*28)+speedStars*100;g.score+=bonus;const final=Math.floor(g.score),old=S.best[g.n]||0;S.best[g.n]=Math.max(old,final);S.unlocked=Math.max(S.unlocked,Math.min(MAX,g.n+1));S.coins+=speedStars;S.stats.wins=(S.stats.wins||0)+1;S.stats.stars=(S.stats.stars||0)+speedStars;save();if(g.n%10===0)award('boss'+g.n,'BOSS CRUSH');if(g.n>=10)award('ten','TEN DOWN');if(g.n>=100)award('hundred','CENTURY');if(g.n===MAX)award('master','MAYHEM MASTER');if(activeChallenge){const day=activeChallenge.day,b=S.challengeBest[day]||0;if(final>b){S.challengeBest[day]=final;S.challengeDone[day]=true;S.challengeStreak=(S.challengeStreak||0)+1;S.coins+=50+g.n;save()}}showOverlay(z.boss?'BOSS DEFEATED':'LEVEL COMPLETE','LEVEL '+g.n,`SCORE <b>${final.toLocaleString()}</b> · ${'★'.repeat(speedStars)}${'☆'.repeat(3-speedStars)}<br>BEST <b>${S.best[g.n].toLocaleString()}</b> · COINS +<b>${speedStars}</b><br>TIME BONUS +<b>${bonus}</b>${final>old?'<br><b>NEW HIGH SCORE</b>':''}`,g.n<MAX?'NEXT LEVEL':'PLAY AGAIN','REPLAY',()=>start(g.n));primary.onclick=()=>start(g.n<MAX?g.n+1:g.n);beep(660,.16,'triangle')}
function update(dt){if(!g||g.paused||g.over)return;const z=cfg(g.n);g.elapsed+=dt;g.time-=dt;if(activeChallenge){if(activeChallenge.timeScale)g.time-=dt*(activeChallenge.timeScale-1);if(activeChallenge.hazardBoost){} }if(g.time<=0)return finish(false);if(g.freeze>0)g.freeze-=dt;if(g.overdrive>0)g.overdrive-=dt;g.spawn-=dt;if(g.spawn<=0&&g.powers.length<2){spawnPower();g.spawn=rand(7,11)}let mx=0,my=0;if(keys.ArrowLeft||keys.a||keys.A)mx--;if(keys.ArrowRight||keys.d||keys.D)mx++;if(keys.ArrowUp||keys.w||keys.W)my--;if(keys.ArrowDown||keys.s||keys.S)my++;if(mx||my){const l=Math.hypot(mx,my)||1;g.m.x=clamp(g.m.x+mx/l*420*dt,20,W-20);g.m.y=clamp(g.m.y+my/l*420*dt,20,H-20);g.drag=true}else if(!g.drag&&g.m){g.drag=false}for(const c of g.cores){if(!c.alive)continue;const dx=g.m.x-c.x,dy=g.m.y-c.y,d=Math.hypot(dx,dy)||1;if(g.drag){const pull=160000/(d*d+170)*(1+S.up.pull*.22);c.vx+=dx/d*pull*dt;c.vy+=dy/d*pull*dt}c.vx*=Math.pow(.025,dt);c.vy*=Math.pow(.025,dt);c.x=clamp(c.x+c.vx*dt,c.r,W-c.r);c.y=clamp(c.y+c.vy*dt,c.r,H-c.r);c.phase+=dt*3;if(d<g.m.r+c.r+9)pull(c)}for(const h of g.hazards){h.a+=h.speed*dt*(g.freeze>0?.12:1);const hx=h.x+Math.cos(h.a+h.phase)*h.orbit,hy=h.y+Math.sin(h.a+h.phase)*h.orbit*.7;for(const c of g.cores)if(c.alive&&Math.hypot(c.x-hx,c.y-hy)<c.r+h.r)hit(c)}if(z.boss){g.boss.a+=dt*.7;const bx=W/2+Math.cos(g.boss.a)*Math.min(W*.3,170),by=H*.25+Math.sin(g.boss.a*1.4)*80;g.boss.x=bx;g.boss.y=by;for(const c of g.cores)if(c.alive&&Math.hypot(c.x-bx,c.y-by)<c.r+g.boss.r)hit(c)}for(const p of g.powers){p.l-=dt;p.a+=dt*4;if(p.l<=0)continue;if(Math.hypot(p.x-g.m.x,p.y-g.m.y)<p.r+g.m.r){if(p.type==='time')g.time=Math.min(z.time+5,g.time+5);if(p.type==='freeze')g.freeze=5;if(p.type==='shield')g.shield=1;if(p.type==='overdrive')g.overdrive=5;msg(p.type.toUpperCase()+'!');particle(p.x,p.y,p.type==='time'?'#ffd45f':p.type==='freeze'?'#58e6ff':p.type==='shield'?'#a98cff':'#ff63b8',35);beep(760,.1,'square');p.l=0}}g.powers=g.powers.filter(p=>p.l>0);if(g.cores.every(c=>!c.alive))return finish(true);for(const p of g.parts){p.l-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.97;p.vy*=.97}g.parts=g.parts.filter(p=>p.l>0);for(const r of g.rings){r.l-=dt;r.r+=140*dt}g.rings=g.rings.filter(r=>r.l>0);for(const f of g.floats){f.l-=dt;f.y-=35*dt}g.floats=g.floats.filter(f=>f.l>0);g.shake=Math.max(0,g.shake-dt);hud()}
function draw(){X.clearRect(0,0,W,H);X.fillStyle='#070914';X.fillRect(0,0,W,H);X.strokeStyle='#151b2e';for(let x=0;x<W;x+=42){X.beginPath();X.moveTo(x,0);X.lineTo(x,H);X.stroke()}for(let y=0;y<H;y+=42){X.beginPath();X.moveTo(0,y);X.lineTo(W,y);X.stroke()}if(!g)return;X.save();if(g.shake)X.translate(rand(-5,5),rand(-5,5));const m=g.m,gl=X.createRadialGradient(m.x,m.y,3,m.x,m.y,125);gl.addColorStop(0,'#8ceaff55');gl.addColorStop(1,'transparent');X.fillStyle=gl;X.beginPath();X.arc(m.x,m.y,125,0,TAU);X.fill();for(const h of g.hazards){const x=h.x+Math.cos(h.a+h.phase)*h.orbit,y=h.y+Math.sin(h.a+h.phase)*h.orbit*.7;X.save();X.translate(x,y);X.rotate(h.a*2);X.shadowBlur=22;X.shadowColor='#ff5577';X.strokeStyle='#ff5577';X.lineWidth=3;X.beginPath();for(let i=0;i<10;i++){const a=i*Math.PI/5,r=i%2?h.r*.5:h.r;X.lineTo(Math.cos(a)*r,Math.sin(a)*r)}X.closePath();X.stroke();X.restore()}if(cfg(g.n).boss){X.shadowBlur=28;X.shadowColor='#ff5577';X.strokeStyle='#ff5577';X.lineWidth=4;X.beginPath();X.arc(g.boss.x,g.boss.y,g.boss.r+Math.sin(g.boss.a*5)*3,0,TAU);X.stroke();X.shadowBlur=0}for(const p of g.powers){const c=p.type==='time'?'#ffd45f':p.type==='freeze'?'#58e6ff':p.type==='shield'?'#a98cff':'#ff63b8';X.save();X.translate(p.x,p.y);X.rotate(p.a);X.strokeStyle=c;X.shadowBlur=20;X.shadowColor=c;X.lineWidth=3;X.beginPath();X.arc(0,0,p.r,0,TAU);X.stroke();X.shadowBlur=0;X.fillStyle=c;X.font='900 11px system-ui';X.textAlign='center';X.textBaseline='middle';X.fillText(p.type==='overdrive'?'2X':p.type[0].toUpperCase(),0,0);X.restore()}for(const c of g.cores)if(c.alive){const q=COL[c.type];X.shadowBlur=22;X.shadowColor=q;X.fillStyle=q;X.beginPath();X.arc(c.x,c.y,c.r+Math.sin(c.phase)*1.5,0,TAU);X.fill();X.shadowBlur=0}for(const r of g.rings){X.globalAlpha=r.l/r.m;X.strokeStyle=r.c;X.lineWidth=2;X.beginPath();X.arc(r.x,r.y,r.r,0,TAU);X.stroke()}for(const p of g.parts){X.globalAlpha=p.l/p.m;X.fillStyle=p.c;X.beginPath();X.arc(p.x,p.y,p.r,0,TAU);X.fill()}X.globalAlpha=1;X.shadowBlur=32;X.shadowColor='#67dcff';X.fillStyle='#effcff';X.beginPath();X.arc(m.x,m.y,m.r,0,TAU);X.fill();X.shadowBlur=0;X.strokeStyle='#4acfff';X.lineWidth=5;X.beginPath();X.arc(m.x,m.y,m.r-3,0,TAU);X.stroke();X.strokeStyle='#091121';X.lineWidth=5;X.beginPath();X.moveTo(m.x-11,m.y);X.lineTo(m.x+11,m.y);X.stroke();if(g.shield){X.strokeStyle='#a98cff';X.setLineDash([5,5]);X.beginPath();X.arc(m.x,m.y,40,0,TAU);X.stroke();X.setLineDash([])}for(const f of g.floats){X.globalAlpha=f.l/.9;X.fillStyle=f.c;X.font='900 14px system-ui';X.textAlign='center';X.fillText(f.t,f.x,f.y)}X.globalAlpha=1;X.restore();if(!g.over){X.fillStyle='#9aa7c8';X.font='900 11px system-ui';X.textAlign='right';X.fillText(Math.ceil(g.time)+'s',W-18,25);X.textAlign='left';if(g.freeze>0){X.fillStyle='#58e6ff';X.fillText('FIELD FROZEN',18,25)}if(g.overdrive>0){X.fillStyle='#ff63b8';X.fillText('2X OVERDRIVE',18,42)}if(activeChallenge){X.fillStyle='#ffd45f';X.fillText('DAILY',18,59)}}}
function loop(t){const dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt);draw();requestAnimationFrame(loop)}
function pointer(e){const r=C.getBoundingClientRect();g.m.x=clamp(e.clientX-r.left,20,W-20);g.m.y=clamp(e.clientY-r.top,20,H-20)}
C.addEventListener('pointerdown',e=>{if(!g||g.over||g.paused)return;pointer(e);g.drag=true;C.setPointerCapture(e.pointerId);beep(220,.03)});C.addEventListener('pointermove',e=>{if(g&&g.drag&&!g.paused)pointer(e)});C.addEventListener('pointerup',()=>{if(g)g.drag=false});C.addEventListener('pointercancel',()=>{if(g)g.drag=false});C.addEventListener('dblclick',()=>{if(!g||g.over||g.paused)return;g.overdrive=5;g.time=Math.min(cfg(g.n).time,g.time+2.5);g.combo=Math.min(15,g.combo+2);msg('OVERDRIVE • 2X');particle(g.m.x,g.m.y,'#fff',35);beep(760,.12,'square')});
addEventListener('keydown',e=>{keys[e.key]=true;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' '].includes(e.key))e.preventDefault();if(e.key==='Escape'&&g&&!g.over){g.paused?resumeGame():pauseGame()}if(e.key.toLowerCase()==='o'&&g&&!g.over){g.overdrive=5;msg('OVERDRIVE • 2X')}});addEventListener('keyup',e=>keys[e.key]=false);
function pauseGame(){if(!g||g.over)return;g.paused=true;showOverlay('PAUSED','MAGNET MAYHEM','LEVEL <b>'+g.n+'</b><br>SCORE <b>'+Math.floor(g.score).toLocaleString()+'</b><br><br>Your progress for this run is kept.','RESUME','QUIT',()=>{hideOverlay();g.over=true;window.openMainMenu&&window.openMainMenu()})}
function resumeGame(){if(g&&!g.over){hideOverlay();g.paused=false}}
window.resumeGame=resumeGame;window.start=start;window.pauseGame=pauseGame;window.magnetState=()=>S;window.magnetSave=save;
pauseBtn.onclick=pauseGame;homeBtn.onclick=()=>window.openMainMenu&&window.openMainMenu();muteBtn.onclick=()=>{muted=!muted;muteBtn.textContent=muted?'SOUND OFF':'SOUND ON'};
window.addEventListener('magnet:daily',(e)=>{activeChallenge=e.detail||null});
requestAnimationFrame(loop);