(()=>{
const stage=document.querySelector('.stage-wrap');if(!stage)return;
const K='magnetMayhemSave',read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}},write=s=>localStorage.setItem(K,JSON.stringify(s));
const menu=document.createElement('div');menu.id='mainMenu';stage.append(menu);
const setPaused=v=>{if(typeof g!=='undefined'&&g)g.paused=v};
const hideOverlay=()=>{const o=document.getElementById('overlay');if(o)o.classList.add('hidden')};
const saveState=()=>{try{if(typeof S!=='undefined')Object.assign(S,read())}catch{}};
const home=()=>{const s=read(),u=Math.max(1,Number(s.unlocked)||1),best=Math.max(0,...Object.values(s.best||{}).map(Number));menu.className='';menu.innerHTML=`<div class="main-menu-card menu-home"><div class="menu-kicker">NEON ARCADE // MAGNETIC CHAOS</div><div class="menu-logo"><span>✦</span><div><b>MAGNET</b><strong>MAYHEM</strong></div></div><p class="menu-tag">Pull the cores. Dodge the hazards. Build the chain.</p><div class="menu-stats"><span><b>LEVEL ${u}</b><small>PROGRESS</small></span><span><b>${Number(s.coins)||0}</b><small>COINS</small></span><span><b>${best.toLocaleString()}</b><small>BEST SCORE</small></span></div><button class="menu-primary" id="menuPlay">${u>1?'CONTINUE · LEVEL '+u:'PLAY'}</button><div class="menu-grid"><button data-page="levels">LEVEL SELECT</button><button data-page="daily">DAILY CHALLENGE</button><button data-page="lab">UPGRADE LAB</button><button data-page="stats">STATS</button><button data-page="medals">MEDALS</button><button data-page="how">HOW TO PLAY</button></div><div class="menu-footer">BUILD 30 · 1,000 LEVELS · BOSSES · POWER-UPS · UPGRADES · DAILY CHALLENGES</div></div>`;
menu.querySelector('#menuPlay').onclick=()=>{menu.classList.add('hidden');hideOverlay();if(typeof start==='function')start(u)};
menu.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>page(b.dataset.page));setPaused(1);hideOverlay()};
const shell=(title,content)=>{menu.className='menu-subpage';menu.innerHTML=`<div class="main-menu-card menu-screen"><button class="menu-back" id="navBack">← BACK</button><div class="menu-kicker">MAGNET MAYHEM // MENU</div><h2>${title}</h2><div class="menu-screen-content">${content}</div></div>`;requestAnimationFrame(()=>menu.querySelector('.menu-screen').classList.add('menu-screen-ready'));menu.querySelector('#navBack').onclick=home;setPaused(1);hideOverlay()};
const page=type=>{
const s=read();
if(type==='levels'){const max=Math.max(1,Math.min(Number(s.unlocked)||1,1000)),best=s.best||{};let h='<div class="level-grid">';for(let n=1;n<=Math.min(max,120);n++)h+=`<button class="level-pick${n%10===0?' boss':''}" data-level="${n}">${n}${best[n]?`<small>BEST ${Math.floor(best[n])}</small>`:''}</button>`;h+='</div>';if(max>120)h+=`<p class="menu-note">${max-120} more levels unlocked. Continue your run to reach them.</p>`;shell('LEVEL SELECT',h);menu.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{menu.classList.add('hidden');if(typeof start==='function')start(Number(b.dataset.level))});return}
if(type==='stats'){const vals=Object.entries(s.best||{}).filter(([,v])=>Number(v)>0).sort((a,b)=>Number(a[0])-Number(b[0]));shell('PLAYER STATS',`<div class="stat-cards"><div><b>${s.unlocked||1}</b><span>UNLOCKED</span></div><div><b>${s.stats?.wins||0}</b><span>CLEARS</span></div><div><b>${s.stats?.stars||0}</b><span>STARS</span></div><div><b>${s.coins||0}</b><span>COINS</span></div></div><h3>HIGH SCORES BY LEVEL</h3><div class="score-list">${vals.length?vals.map(([n,v])=>`<div><span>LEVEL ${n}</span><b>${Math.floor(v).toLocaleString()}</b></div>`).join(''):'<p class="menu-note">Complete a level to record its high score.</p>'}</div>`);return}
if(type==='medals'){shell('MEDALS',`<div class="medal-copy"><b>${(s.ach||[]).length} UNLOCKED</b><p>FIRST PULL — collect your first core</p><p>CHAIN REACTION — reach x8 combo</p><p>TEN DOWN — reach level 10</p><p>CENTURY — reach level 100</p><p>MAYHEM MASTER — conquer level 1000</p><p>Boss medals are earned every 10th level.</p></div>`);return}
if(type==='how'){shell('HOW TO PLAY',`<div class="help-list"><div><b>MOVE</b><span>Drag or hold on the field. Keyboard: WASD, arrows or IJKL.</span></div><div><b>PULL</b><span>Get close to glowing cores while holding to pull them into the magnet.</span></div><div><b>SURVIVE</b><span>Avoid moving hazards. Your shield can absorb one hit.</span></div><div><b>CHAIN</b><span>Collect cores quickly to build your combo and maximize your score.</span></div><div><b>POWER</b><span>Collect Time, Freeze, Shield and 2X power-ups.</span></div></div>`);return}
if(type==='lab'){const up=Object.assign({pull:0,time:0,shield:0,core:0,stability:0},s.up||{}),names={pull:['MAGNET POWER','Stronger pull',8,1.65],time:['TIME CORE','More starting time',10,1.7],shield:['SHIELD MATRIX','Extra shield capacity',15,1.8],core:['CORE AMPLIFIER','Higher core score',18,1.75],stability:['STABILITY FIELD','Combo recovery',22,1.8]};let h=`<div class="lab-balance"><b>COINS: <span id="labCoins">${s.coins||0}</span></b></div><div class="upgrade-list">`;for(const [k,d] of Object.entries(names)){const cost=Math.round(d[2]*Math.pow(d[3],up[k]));h+=`<div class="upgrade-row"><div><b>${d[0]}</b><small>LV ${up[k]} · ${d[1]}</small></div><button data-up="${k}" data-cost="${cost}">BUY · ${cost}</button></div>`}h+='</div>';shell('UPGRADE LAB',h);menu.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{let s=read(),u=Object.assign({pull:0,time:0,shield:0,core:0,stability:0},s.up||{}),k=b.dataset.up,c=Number(b.dataset.cost);if((s.coins||0)<c){b.textContent='NOT ENOUGH COINS';return}s.coins-=c;u[k]++;s.up=u;write(s);saveState();page('lab')});return}
if(type==='daily'){const c=typeof window.magnetDailyChallenge==='function'?window.magnetDailyChallenge():null;if(!c){shell('DAILY CHALLENGE','<p class="menu-note">Daily Challenge unavailable.</p>');return}const best=Number(s.challengeBest?.[c.day])||0,done=!!s.challengeDone?.[c.day];shell('DAILY CHALLENGE',`<div class="challenge-card"><b>FIELD ${c.level}</b><span>${c.tag}</span></div><p>${c.description}</p><div class="challenge-stats"><span><b>${best||'—'}</b><small>TODAY'S BEST</small></span><span><b>${s.challengeStreak||0}</b><small>DAY STREAK</small></span><span><b>+${50+c.level}</b><small>COIN REWARD</small></span></div>${done?'<div class="challenge-complete">✓ COMPLETED TODAY</div>':''}<button class="menu-primary" id="playDaily">PLAY CHALLENGE</button>`);menu.querySelector('#playDaily').onclick=()=>{menu.classList.add('hidden');window.magnetChallengeActive=c;if(typeof start==='function')start(c.level)};return}
};
const show=()=>{home()};const homeBtn=document.getElementById('homeBtn');if(homeBtn)homeBtn.onclick=show;menu.style.pointerEvents='auto';show();
})();