(()=>{
'use strict';
const stage=document.querySelector('.stage-wrap');if(!stage)return;
const KEY='magnetMayhemSave',MAX=1000;
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const write=s=>localStorage.setItem(KEY,JSON.stringify(s));
const menu=document.createElement('div');menu.id='mainMenu';stage.append(menu);
const pause=v=>{if(window.g)window.g.paused=v};
const launch=n=>{menu.classList.add('hidden');pause(false);window.start?.(n)};
const shell=(title,body)=>{menu.className='mm-page';menu.innerHTML=`<div class="mm-card mm-inner"><button class="mm-back">← MENU</button><small class="mm-label">MAGNET MAYHEM</small><h2>${title}</h2>${body}</div>`;pause(true);menu.querySelector('.mm-back').onclick=home};
function home(){const s=read(),u=Math.max(1,Math.min(MAX,+s.unlocked||1)),best=Math.max(0,...Object.values(s.best||{}).map(Number));menu.className='mm-home';menu.innerHTML=`<div class="mm-card"><div class="mm-brand"><span>✦</span><div><small>NEON MAGNETIC ARCADE</small><b>MAGNET</b><strong>MAYHEM</strong></div></div><p class="mm-sub">PULL • DODGE • CHAIN • SURVIVE</p><div class="mm-stats"><div><b>${u}</b><small>LEVEL</small></div><div><b>${s.coins||0}</b><small>COINS</small></div><div><b>${best.toLocaleString()}</b><small>BEST</small></div></div><button class="mm-btn primary" id="continue">${u>1?'CONTINUE · LEVEL '+u:'START GAME'}</button><div class="mm-nav"><button class="mm-btn" data-p="levels">LEVELS</button><button class="mm-btn" data-p="upgrades">UPGRADES</button><button class="mm-btn" data-p="daily">DAILY</button><button class="mm-btn" data-p="stats">STATS</button><button class="mm-btn" data-p="medals">MEDALS</button><button class="mm-btn" data-p="how">HOW TO PLAY</button></div><div class="mm-foot">1,000 LEVELS · BOSS EVERY 10 · POWER-UPS · COMBOS</div></div>`;pause(true);menu.querySelector('#continue').onclick=()=>launch(u);menu.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>pages[b.dataset.p]())}
const pages={
levels(){const s=read(),max=Math.max(1,Math.min(MAX,+s.unlocked||1));let h='<div class="mm-levels">';for(let n=1;n<=max;n++)h+=`<button class="${n%10===0?'boss':''}" data-l="${n}"><b>${n}</b>${s.best?.[n]?`<small>${Math.floor(s.best[n]).toLocaleString()}</small>`:''}</button>`;h+='</div>';shell('LEVEL SELECT',h);menu.querySelectorAll('[data-l]').forEach(b=>b.onclick=()=>launch(+b.dataset.l))},
upgrades(){const s=read(),u={pull:0,time:0,shield:0,core:0,stability:0,...(s.up||{})},d={pull:['MAGNET POWER','Stronger magnetic pull',8,1.65],time:['TIME CORE','More starting time',10,1.7],shield:['SHIELD MATRIX','Start protected',15,1.8],core:['CORE AMPLIFIER','Higher pickup score',18,1.75],stability:['STABILITY FIELD','Protect your combo',22,1.8]};let h=`<div class="mm-coins">COINS <b>${s.coins||0}</b></div><div class="mm-list">`;for(const[k,x]of Object.entries(d)){const cost=Math.round(x[2]*Math.pow(x[3],u[k]||0));h+=`<div><span><b>${x[0]}</b><small>LEVEL ${u[k]||0} · ${x[1]}</small></span><button data-u="${k}" data-c="${cost}">BUY ${cost}</button></div>`}h+='</div>';shell('UPGRADE LAB',h);menu.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{const s=read(),u={pull:0,time:0,shield:0,core:0,stability:0,...(s.up||{})},k=b.dataset.u,c=+b.dataset.c;if((s.coins||0)<c){b.textContent='NEED COINS';return}s.coins-=c;u[k]++;s.up=u;write(s);pages.upgrades()})},
daily(){const s=read(),day=new Date().toISOString().slice(0,10),seed=[...day].reduce((a,c)=>(a*31+c.charCodeAt(0))>>>0,17),max=Math.max(1,+s.unlocked||1),level=1+seed%max,boss=level%10===0||seed%5===0?Math.max(1,level-level%10):level;const best=s.challengeBest?.[day]||0;s.challenge={day,level:boss};write(s);shell('DAILY CHALLENGE',`<div class="mm-challenge"><small>TODAY'S FIELD</small><b>${boss}</b><span>ONE RUN · ONE RECORD</span><strong>${best?Number(best).toLocaleString():'—'}</strong><small>DAILY BEST</small></div><button class="mm-btn primary" id="daily">PLAY DAILY</button>`);menu.querySelector('#daily').onclick=()=>{window.magnetChallengeActive={day,level:boss};launch(boss)}},
stats(){const s=read(),vals=Object.entries(s.best||{}).sort((a,b)=>+a[0]-+b[0]);shell('PLAYER STATS',`<div class="mm-bigstats"><div><b>${s.unlocked||1}</b><small>UNLOCKED</small></div><div><b>${s.stats?.wins||0}</b><small>CLEARS</small></div><div><b>${s.stats?.cores||0}</b><small>CORES</small></div><div><b>${s.coins||0}</b><small>COINS</small></div></div><h3>LEVEL RECORDS</h3><div class="mm-scores">${vals.length?vals.map(([n,v])=>`<div><span>LEVEL ${n}</span><b>${Math.floor(v).toLocaleString()}</b></div>`).join(''):'<p>No records yet.</p>'}</div>`)},
medals(){const m=read().medals||[];shell('MEDALS',`<div class="mm-medals"><div>✦ <b>FIRST PULL</b><small>${m.includes('first')?'UNLOCKED':'LOCKED'} · First core collected</small></div><div>✦ <b>CHAIN REACTION</b><small>${m.includes('combo')?'UNLOCKED':'LOCKED'} · x8 combo</small></div><div>✦ <b>TEN DOWN</b><small>${m.includes('ten')?'UNLOCKED':'LOCKED'} · Level 10</small></div><div>✦ <b>CENTURY</b><small>${m.includes('hundred')?'UNLOCKED':'LOCKED'} · Level 100</small></div><div>✦ <b>MAYHEM MASTER</b><small>${m.includes('master')?'UNLOCKED':'LOCKED'} · Level 1000</small></div></div>`)},
how(){shell('HOW TO PLAY',`<div class="mm-help"><div><b>MOVE</b><span>Drag the magnet, or use WASD / arrow keys.</span></div><div><b>COLLECT</b><span>Pull glowing cores into the magnet before their timer expires.</span></div><div><b>SCORE</b><span>Fast pickups score more. Consecutive pickups build your combo.</span></div><div><b>SURVIVE</b><span>Avoid red hazards. Hits can break your combo; shields absorb damage.</span></div><div><b>POWER-UPS</b><span>TIME, FREEZE, SHIELD and OVERDRIVE can turn a run around.</span></div><div><b>BOSSES</b><span>Every 10th level adds a boss encounter and extra pressure.</span></div></div>`)}
};
window.openMainMenu=home;window.openMainMenuPage=k=>pages[k]?.();document.getElementById('homeBtn').onclick=home;document.getElementById('shopBtn').onclick=pages.upgrades;home();
})();