(()=>{
const KEY='magnetMayhemProfile',SAVE='magnetMayhemSave',avatars=['🧲','⚡','🌌','🔥','💎','☄️','🤖','👾'];
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY))||null}catch{return null}},save=()=>{try{return JSON.parse(localStorage.getItem(SAVE))||{}}catch{return{}}},write=p=>localStorage.setItem(KEY,JSON.stringify(p));
const stage=document.querySelector('.stage-wrap');if(!stage)return;const box=document.createElement('div');box.id='profilePanel';box.className='profile-panel hidden';stage.append(box);
function open(){box.classList.remove('hidden');render(read())}function close(){box.classList.add('hidden')}
function render(p){const s=save(),u=s.unlocked||1,best=Math.max(0,...Object.values(s.best||{}).map(Number));
if(!p){box.innerHTML=`<div class="profile-card"><div class="menu-kicker">PLAYER ACCOUNT</div><h2>CREATE YOUR PROFILE</h2><p class="profile-sub">Create an identity for Magnet Mayhem.</p><form id="profileForm"><input id="regName" maxlength="18" placeholder="Username" required autocomplete="nickname"><input id="regEmail" type="email" placeholder="Email" autocomplete="email"><div class="avatar-grid">${avatars.map((a,i)=>`<button type="button" class="avatar-pick${i===0?' selected':''}" data-avatar="${a}">${a}</button>`).join('')}</div><input id="regPass" type="password" minlength="6" placeholder="Password" required autocomplete="new-password"><button class="menu-primary" type="submit">CREATE ACCOUNT</button></form><button class="profile-back" id="appleAccount"> &nbsp; SIGN IN WITH APPLE</button><button class="profile-back" id="profileClose">BACK</button></div>`;let avatar=avatars[0];box.querySelectorAll('.avatar-pick').forEach(b=>b.onclick=()=>{box.querySelectorAll('.avatar-pick').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');avatar=b.dataset.avatar});box.querySelector('#profileForm').onsubmit=e=>{e.preventDefault();const n=box.querySelector('#regName').value.trim(),em=box.querySelector('#regEmail').value.trim(),pw=box.querySelector('#regPass').value;if(n.length<2||pw.length<6)return alert('Username must be 2+ characters and password 6+ characters.');write({username:n,email:em,avatar,passwordSet:true,createdAt:new Date().toISOString(),provider:'email'});render(read())};box.querySelector('#appleAccount').onclick=()=>window.magnetOpenAccount?.();box.querySelector('#profileClose').onclick=close;return}
box.innerHTML=`<div class="profile-card"><div class="profile-top"><div class="profile-avatar">${p.avatar||'🧲'}</div><div><div class="menu-kicker">PLAYER PROFILE</div><h2>${escapeHtml(p.username)}</h2><span class="profile-email">${escapeHtml(p.email||'Apple / private relay')}</span></div></div><div class="profile-stats"><span><b>LEVEL ${u}</b><small>PROGRESS</small></span><span><b>${Number(s.coins)||0}</b><small>COINS</small></span><span><b>${best.toLocaleString()}</b><small>BEST</small></span></div><div class="avatar-grid">${avatars.map(a=>`<button type="button" class="avatar-pick${a===p.avatar?' selected':''}" data-avatar="${a}">${a}</button>`).join('')}</div><button class="menu-primary" id="profileSave">SAVE AVATAR</button><button class="profile-back" id="profileLogout">LOG OUT</button><button class="profile-back" id="profileClose">BACK</button></div>`;box.querySelectorAll('.avatar-pick').forEach(b=>b.onclick=()=>{box.querySelectorAll('.avatar-pick').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')});box.querySelector('#profileSave').onclick=()=>{p.avatar=box.querySelector('.avatar-pick.selected')?.dataset.avatar||p.avatar;write(p);render(p)};box.querySelector('#profileLogout').onclick=()=>{localStorage.removeItem(KEY);render(null)};box.querySelector('#profileClose').onclick=close}
function escapeHtml(x){return String(x).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
const b=document.createElement('button');b.type='button';b.className='controls button';b.textContent='PROFILE';b.onclick=open;document.querySelector('.controls')?.prepend(b);const menu=document.getElementById('mainMenu');if(menu){const grid=menu.querySelector('.menu-grid');if(grid){const pb=document.createElement('button');pb.textContent='PROFILE / ACCOUNT';grid.append(pb);pb.onclick=open}}
window.magnetProfile={open,close,read};
})();
