(()=>{
const K='magnetMayhemSave';
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};
const write=s=>localStorage.setItem(K,JSON.stringify(s));
const ov=document.getElementById('overlay'),ok=document.getElementById('overlayKicker'),ot=document.getElementById('overlayTitle'),ox=document.getElementById('overlayText'),pb=document.getElementById('primaryBtn'),sb=document.getElementById('secondaryBtn');
const state=()=>{let s=read();s.coins=s.coins||0;s.up=Object.assign({pull:0,time:0,shield:0,core:0,stability:0},s.up||{});s.ach=s.ach||[];s.stats=s.stats||{wins:0,cores:0,stars:0,bosses:0};s.mastery=s.mastery||{milestones:[],clears:0};s.skins=s.skins||['classic'];s.skin=s.skin||'classic';return s};
const cost=(key,s)=>({pull:Math.round(8*Math.pow(1.65,s.up.pull)),time:Math.round(10*Math.pow(1.7,s.up.time)),shield:Math.round(15*Math.pow(1.8,s.up.shield)),core:Math.round(18*Math.pow(1.75,s.up.core)),stability:Math.round(22*Math.pow(1.8,s.up.stability))}[key]);
let resume=()=>{};
function openPanel(){if(typeof g!=='undefined'&&g&&!g.over){const was=!g.paused;g.paused=1;resume=()=>{if(typeof g!=='undefined'&&g&&!g.over&&was)g.paused=0}}else resume=()=>{}}
function closePanel(){ov.classList.add('hidden');resume();resume=()=>{}}
function shop(){openPanel();let s=state();ov.classList.remove('hidden');ok.textContent='MAYHEM LAB';ot.textContent='UPGRADE SHOP';ox.innerHTML=`<b>COINS: ${s.coins}</b><br><br><div style="text-align:left;line-height:1.55">${[['pull','MAGNET POWER','Stronger pull'],['time','TIME CORE','More starting time'],['shield','SHIELD MATRIX','Extra shield charges'],['core','CORE AMPLIFIER','Higher core score'],['stability','STABILITY FIELD','Combo recovery']].map(a=>`<b>${a[1]}</b> · Lv ${s.up[a[0]]}<br><small>${a[2]}</small><br><button class="secondary" data-up="${a[0]}">BUY · ${cost(a[0],s)} COINS</button><br>`).join('<br>')}</div>`;pb.textContent='BACK';pb.onclick=closePanel;sb.classList.add('hidden');ox.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{let s=state(),k=b.dataset.up,c=cost(k,s);if(s.coins<c){b.textContent='NOT ENOUGH COINS';return}s.coins-=c;s.up[k]++;write(s);shop()})}
window.openUpgradeLab=shop;
const btn=document.getElementById('shopBtn');if(btn)btn.onclick=shop;
const ach=document.createElement('button');ach.type='button';ach.textContent='MEDALS';ach.className='controls button';function medals(){openPanel();let s=state(),m=s.mastery.milestones||[];ok.textContent='HALL OF FAME';ot.textContent='MEDALS';ox.innerHTML=`<b>${s.ach.length} UNLOCKED</b><br><br>FIRST PULL — collect your first core<br>CHAIN REACTION — reach x8 combo<br>TEN DOWN — reach level 10<br>CENTURY — reach level 100<br>MAYHEM MASTER — conquer level 1000<br><br><b>MASTERY</b><br>${m.length} milestone rewards claimed · ${s.mastery.clears||0} total clears<br>Milestones: 10 / 50 / 100 / 200 / 300 / 400 / 500 / 600 / 700 / 800 / 900 / 1000<br><br>Boss medals are earned every 10th level.`;pb.textContent='BACK';pb.onclick=closePanel;sb.classList.add('hidden')};window.openMedals=medals;ach.onclick=medals;document.querySelector('.controls').prepend(ach);
const stats=document.createElement('button');stats.type='button';stats.textContent='STATS';stats.className='controls button';function showStats(){openPanel();let s=state(),stars=s.stats.stars||0,cores=s.stats.cores||0,wins=s.stats.wins||0,bosses=s.stats.bosses||0,best=Object.values(s.best||{}).reduce((a,v)=>Math.max(a,Number(v)||0),0),next=[10,50,100,200,300,400,500,600,700,800,900,1000].find(n=>!s.mastery.milestones.includes(n))||'COMPLETE';ok.textContent='MAYHEM RECORD';ot.textContent='PLAYER STATS';ox.innerHTML=`<b>LEVEL ${s.unlocked||1}</b><br><br>LEVELS CLEARED · ${wins}<br>CORES COLLECTED · ${cores}<br>BOSS LEVELS CLEARED · ${bosses}<br>STARS EARNED · ${stars}<br>COINS · ${s.coins}<br>BEST SCORE · ${best}<br><br><b>UPGRADES</b><br>MAGNET POWER Lv ${s.up.pull} · TIME CORE Lv ${s.up.time}<br>SHIELD MATRIX Lv ${s.up.shield} · CORE AMPLIFIER Lv ${s.up.core}<br>STABILITY FIELD Lv ${s.up.stability}<br><br><b>MASTERY</b><br>TOTAL CLEARS · ${s.mastery.clears||0}<br>MILESTONES · ${s.mastery.milestones.length}<br>NEXT MILESTONE · ${next}<br>MAGNET SKIN · ${(s.skin||'classic').toUpperCase()}`;pb.textContent='BACK';pb.onclick=closePanel;sb.classList.add('hidden')};window.openStats=showStats;stats.onclick=showStats;document.querySelector('.controls').prepend(stats);
})();