(()=>{
const K='magnetMayhemSave';
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};
const write=s=>localStorage.setItem(K,JSON.stringify(s));
const ov=document.getElementById('overlay'),ok=document.getElementById('overlayKicker'),ot=document.getElementById('overlayTitle'),ox=document.getElementById('overlayText'),pb=document.getElementById('primaryBtn'),sb=document.getElementById('secondaryBtn'),home=document.getElementById('homeBtn');
const state=()=>{let s=read();s.coins=s.coins||0;s.up=s.up||{pull:0,time:0,shield:0};return s};
const cost=(key,s)=>({pull:Math.round(8*Math.pow(1.65,s.up.pull)),time:Math.round(10*Math.pow(1.7,s.up.time)),shield:Math.round(15*Math.pow(1.8,s.up.shield))}[key]);
function shop(){let s=state();ov.classList.remove('hidden');ok.textContent='MAYHEM LAB';ot.textContent='UPGRADE SHOP';ox.innerHTML=`<b>COINS: ${s.coins}</b><br><br><div style="text-align:left;line-height:2"><b>MAGNET POWER</b> · Lv ${s.up.pull}<br><small>Stronger pull force</small><br><button class="secondary" data-up="pull">BUY · ${cost('pull',s)} COINS</button><br><br><b>TIME CORE</b> · Lv ${s.up.time}<br><small>More starting time</small><br><button class="secondary" data-up="time">BUY · ${cost('time',s)} COINS</button><br><br><b>SHIELD MATRIX</b> · Lv ${s.up.shield}<br><small>Start with a shield</small><br><button class="secondary" data-up="shield">BUY · ${cost('shield',s)} COINS</button></div>`;pb.textContent='BACK';pb.onclick=()=>{ov.classList.add('hidden')};sb.classList.add('hidden');ox.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{let s=state(),k=b.dataset.up,c=cost(k,s);if(s.coins<c){b.textContent='NOT ENOUGH COINS';return}s.coins-=c;s.up[k]++;write(s);shop()})}
const btn=document.createElement('button');btn.id='shopBtn';btn.type='button';btn.textContent='LAB';btn.className='icon-btn';btn.title='Upgrade Lab';document.querySelector('.hud').insertBefore(btn,document.getElementById('pauseBtn'));btn.onclick=shop;
const ach=document.createElement('button');ach.type='button';ach.textContent='MEDALS';ach.className='controls button';ach.onclick=()=>{let s=state();ov.classList.remove('hidden');ok.textContent='HALL OF FAME';ot.textContent='MEDALS';ox.innerHTML=`<b>${s.ach?.length||0} UNLOCKED</b><br><br>FIRST PULL — collect your first core<br>CHAIN REACTION — reach x8 combo<br>TEN DOWN — reach level 10<br>CENTURY — reach level 100<br>MAYHEM MASTER — conquer level 1000<br><br>Boss medals are earned every 10th level.`;pb.textContent='BACK';pb.onclick=()=>ov.classList.add('hidden');sb.classList.add('hidden')};document.querySelector('.controls').prepend(ach);
})();
