(()=>{
const K='magnetMayhemSave',ov=document.getElementById('overlay'),ok=document.getElementById('overlayKicker'),ot=document.getElementById('overlayTitle'),ox=document.getElementById('overlayText'),pb=document.getElementById('primaryBtn'),sb=document.getElementById('secondaryBtn');
const read=()=>{try{return JSON.parse(localStorage.getItem(K))||{}}catch{return{}}};const save=s=>{localStorage.setItem(K,JSON.stringify(s));try{Object.assign(S,s)}catch{}};
const skins={classic:['CLASSIC',0,'Original'],plasma:['PLASMA',18,'Hot pink energy'],gold:['GOLD',28,'Gold alloy'],void:['VOID',40,'Violet singularity'],emerald:['EMERALD',55,'Emerald pulse']};
const costs=(k,l)=>Math.round(({pull:8,time:10,shield:15,core:18,stability:22}[k]||8)*Math.pow({pull:1.65,time:1.7,shield:1.8,core:1.75,stability:1.8}[k]||1.7,l));let resume=()=>{};
function panel(){if(g&&!g.over){let was=!g.paused;g.paused=1;resume=()=>{if(g&&!g.over&&was)g.paused=0}}}
function close(){ov.classList.add('hidden');resume();resume=()=>{}}
function lab(){panel();let s=read();s.up=Object.assign({pull:0,time:0,shield:0,core:0,stability:0},s.up||{});ov.classList.remove('hidden');ok.textContent='MAYHEM LAB';ot.textContent='UPGRADE BRANCHES';ox.innerHTML=`<b>COINS: ${s.coins||0}</b><br><br><div style="text-align:left;line-height:1.55">${[['pull','MAGNET POWER','Stronger pull'],['time','TIME CORE','More starting time'],['shield','SHIELD MATRIX','Extra shield charges'],['core','CORE AMPLIFIER','Higher core score'],['stability','STABILITY FIELD','Combo recovery']].map(a=>`<b>${a[1]}</b> · Lv ${s.up[a[0]]}<br><small>${a[2]}</small><br><button class="secondary" data-up="${a[0]}">BUY · ${costs(a[0],s.up[a[0]])} COINS</button><br>`).join('<br>')}</div>`;pb.textContent='BACK';pb.onclick=close;sb.classList.remove('hidden');sb.textContent='MAGNET SKINS';sb.onclick=skin;ox.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>{let s=read();s.coins=s.coins||0;s.up=Object.assign({pull:0,time:0,shield:0,core:0,stability:0},s.up||{});let k=b.dataset.up,c=costs(k,s.up[k]);if(s.coins<c){b.textContent='NOT ENOUGH COINS';return}s.coins-=c;s.up[k]++;save(s);lab()})}
function skin(){panel();let s=read();s.skins=s.skins||['classic'];s.skin=s.skin||'classic';ov.classList.remove('hidden');ok.textContent='MAYHEM GARAGE';ot.textContent='MAGNET SKINS';ox.innerHTML=`<b>COINS: ${s.coins||0}</b><br><br>`+Object.entries(skins).map(([id,d])=>{let owned=s.skins.includes(id),eq=s.skin===id;return `<div style="text-align:left;margin:10px 0"><b>${d[0]}</b> ${eq?'· EQUIPPED':''}<br><small>${d[2]}</small><br><button class="secondary" data-skin="${id}">${eq?'EQUIPPED':owned?'EQUIP':'UNLOCK · '+d[1]+' COINS'}</button></div>`}).join('');pb.textContent='BACK';pb.onclick=lab;sb.classList.remove('hidden');sb.textContent='UPGRADES';sb.onclick=lab;ox.querySelectorAll('[data-skin]').forEach(b=>b.onclick=()=>{let s=read();s.skins=s.skins||['classic'];let id=b.dataset.skin,d=skins[id];if(!s.skins.includes(id)){if((s.coins||0)<d[1]){b.textContent='NOT ENOUGH COINS';return}s.coins-=d[1];s.skins.push(id)}s.skin=id;save(s);skin()})}
const btn=document.getElementById('shopBtn');if(btn)btn.onclick=lab;
let lastScore=0,lastCombo=1;
function runtime(){if(typeof g==='undefined'||!g)return;let s=read(),u=Object.assign({core:0,stability:0},s.up||{});let gain=g.score-lastScore;if(gain>0&&u.core){g.score+=gain*(u.core*.08);gain=g.score-lastScore}lastScore=g.score;if(g.combo>lastCombo)lastCombo=g.combo;if(g.combo===1&&lastCombo>1&&u.stability){g.combo=Math.min(15,Math.max(1,Math.floor(lastCombo*(.35+.1*u.stability))));lastCombo=g.combo}if(g.over||g.n!==runtime.level){runtime.level=g.n;lastCombo=g.combo}let maxShield=1+Math.floor((u.shield||0)/3);if(g.shield>maxShield)g.shield=maxShield}
function skinDraw(){if(typeof g==='undefined'||!g||g.over||g.paused)return;let s=read(),id=s.skin||'classic',d=skins[id]||skins.classic,C=document.getElementById('game'),ctx=C.getContext('2d'),m=g.m;let colors={classic:'#58e6ff',plasma:'#ff63b8',gold:'#ffd45f',void:'#a98cff',emerald:'#7df5a1'},c=colors[id];ctx.save();ctx.shadowBlur=34;ctx.shadowColor=c;ctx.fillStyle=c;ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle='#effcff';ctx.beginPath();ctx.arc(m.x,m.y,m.r-5,0,Math.PI*2);ctx.fill();ctx.strokeStyle=c;ctx.lineWidth=4;ctx.beginPath();ctx.arc(m.x,m.y,m.r-3,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#091121';ctx.lineWidth=5;ctx.beginPath();ctx.moveTo(m.x-11,m.y);ctx.lineTo(m.x+11,m.y);ctx.stroke();if(id==='void'){ctx.strokeStyle='#fff';ctx.globalAlpha=.45;ctx.beginPath();ctx.arc(m.x,m.y,38+Math.sin(performance.now()/160)*3,0,Math.PI*2);ctx.stroke()}ctx.restore()}
function loop(){runtime();skinDraw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
})();
